### ISSUE TITLE
node-gyp builds crap binaries

### ISSUE THREAD

**Issue by alexhultman** [alexhultman/uWebSockets#101]
node-gyp adds flags that I do not want. Flags that makes no sense and only worsen performance and functionalities. node-gyp should build with **exactly** the same flags as the Makefile does. node-gyp adds bad optimization levels, disables aggressive optimizations and adds a ton of other bullshit flags it shouldn't even touch.

**Comment by kapouer** [comment]
i'll have a look at this. Looks related to https://github.com/nodejs/node-gyp/issues/26

**Comment by lpinca** [comment]
I'm posting here the discussion in https://github.com/alexhultman/uWebSockets/commit/d4e56bd1bef6939781d91121832601d5eaba0b24 as it's relevant.
