### ISSUE TITLE
terminate called after throwing an instance of 'std:logic_error'

### ISSUE THREAD

**Issue by kapouer** [alexhultman/uWebSockets#103]
Using master @ https://github.com/alexhultman/uWebSockets/commit/d4e56bd1bef6939781d91121832601d5eaba0b24:
```
2016-05-11_20:43:09.82135 terminate called after throwing an instance of 'std::logic_error'
2016-05-11_20:43:09.82139   what():  basic_string::_M_construct null not valid
```

This doesn't happen so often.

**Comment by alexhultman** [comment]
Did this ever happen in 0.4.0?

**Comment by kapouer** [comment]
It has been happening a dozen times a day since the 7th of may, and in between i've been running pre-0.4.0, 0.4.0, and master. So yes ! Almost certain it does happen with 0.4.0. The load on the socket.io server has been very light these days, so i suppose it's not an uncommon situation (max 400 clients, with a mix of ws and long-polling clients).

**Comment by alexhultman** [comment]
Could you compile with -g and run node in gdb? I think you'll get the exact place where it fails then.

**Comment by alexhultman** [comment]
Do you run SSL?

**Comment by kapouer** [comment]
The failure happens on a non-ssl application. There is a ssl application but it's for < 10 clients and i don't see the failure there.

**Comment by alexhultman** [comment]
12a4654d7746f357ea53a29a9f93eea68b9c0bd1

The only places where I use std::string, and also the only places where std::string can throw anything like std::logic_error is when appending, so I just added some error printings there. Could you see if this catches the exception and also report if the output is messed up.

**Comment by kapouer** [comment]
Installed, rebuilt with `-g`, and running with `catchsegv`

**Comment by alexhultman** [comment]
You should probably run it in gdb as this isn't a segmentation fault. It shouldn't be append that fails..

**Comment by alexhultman** [comment]
What version of GCC do you have, this is Linux right?

**Comment by kapouer** [comment]
Yes, a debian testing

**Comment by alexhultman** [comment]
I can get it to fail by sending an upgrade header without the secKey:

```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted (core dumped)
```

This happens because in addon.cpp in NativeString I give any Undefined Value the string nullptr, which then gets passed to std::string constructor which fails if given nullptr. I get _S_construct but it seems to be the same problem.

You could trigger this bug by modifying bench1 to not send secKey and see how yours react

**Comment by alexhultman** [comment]
I commented out this line in bench1:

```
    const char *buf = "GET /default HTTP/1.1\r\n"
                      "Host: server.example.com\r\n"
                      "Upgrade: websocket\r\n"
                      "Connection: Upgrade\r\n"
                      //"Sec-WebSocket-Key: x3JJHMbDL1EzLkh9GBhXDw==\r\n"
                      "Sec-WebSocket-Protocol: default\r\n"
                      "Sec-WebSocket-Version: 13\r\n"
                      "Origin: http://example.com\r\n\r\n";
```

**Comment by alexhultman** [comment]
Latest commit should deny invalid upgrades, please take this for a spin and see if it works better.

**Comment by kapouer** [comment]
that one seems gone now

**Comment by kapouer** [comment]
Ok, now with > 2000 clients i don't see this bug any more.

**Comment by kapouer** [comment]
Yes, and it's a somewhat standard debian/testing install. I'm using nodejs debian package from sid as well, could that make a difference ?

**Comment by alexhultman** [comment]
I have no idea, these things are internal to libstdc++ and I don't see any obvious convention other than _M_construct might be the move constructor while _S_construct is the regular constructor. There is a possibility that both could be used, depending on optimization level but I have no idea. As long as it never happens again.
