### ISSUE TITLE
Listen on multiple ports (feature request)

### ISSUE THREAD

**Issue by jimmyt857** [alexhultman/uWebSockets#108]
Currently, if I want to listen on multiple ports, it seems like I need to create a separate Server for each port. However, since under the hood each Server has its own libuv event loop, this creates multiple threads and also requires locking when communication between Server objects is required. Would it be possible to perhaps pass a list of ports to a Server instead of a single value?

**Comment by alexhultman** [comment]
You need one server per port but you can use the same thread and the same uv loop:

Server s1(port1);
Server s2(port2);

s1.run(); // this runs both servers (they share the same loop)

**Comment by jimmyt857** [comment]
Oh, I didn't notice that, my apologies. Thanks!

**Comment by alexhultman** [comment]
It's not documented so it's hard to notice :P
