### ISSUE TITLE
_socket remoteFamily

### ISSUE THREAD

**Issue by jondubois** [alexhultman/uWebSockets#110]
The socket.connection in Node.js has a remoteFamily property (to check if the IP address is IPv4 or IPv6) it would be nice if we could also have this in uws for consistency (in the _socket object here https://github.com/alexhultman/uWebSockets/blob/master/nodejs/dist/uws.js#L144-L149)  but it's not an emergency.

**Comment by alexhultman** [comment]
This should be fixed in master now.
