### ISSUE TITLE
Limit size of messages received by the server from jsland

### ISSUE THREAD

**Issue by LordMajestros** [alexhultman/uWebSockets#114]
Is there an option like maxMessageSize to limit the size of messages sent to the server? Is there an option for this from javascript?

**Comment by alexhultman** [comment]
Nope this is not done yet. How does ws do this? What's the option name?

**Comment by SEAPUNK** [comment]
ws does it with the option 'maxPayload', but I'm not sure the option is documented.

**Comment by LordMajestros** [comment]
It's called maxPayload https://github.com/websockets/ws/blob/master/lib/WebSocketServer.js#L40
Ws discards messages >maxPayload length. I wrote the

**Comment by SEAPUNK** [comment]
I know that it maintains a "buffer" that keeps track of how large the message is, but I don't know if it does it only for fragmented messages, or if it reads the frame sizes as well, discarding them immediately if they're too big.

**Comment by LordMajestros** [comment]
@seapunk it does it for compressed/fragmented messages as well https://github.com/websockets/ws/blob/master/lib/PerMessageDeflate.js#L14

**Comment by LordMajestros** [comment]
@alexhultman you had a similar option for lws I think.

**Comment by alexhultman** [comment]
This is now in master. Truncation currently, might change to drop the frame completely.

**Comment by LordMajestros** [comment]
Great job!
