### ISSUE TITLE
Add custom events to libuv event loop

### ISSUE THREAD

**Issue by jimmyt857** [alexhultman/uWebSockets#115]
Similar to my previous request of running multiple servers on one thread, I also want to be able to queue up my own tasks on the same libuv event loop so that synchronization is not necessary and I avoid the overhead of multiple threads.

This is very important for my project, so I'll write this myself when I have some time and submit a pull request. Before I begin, I want to know your opinion on the additional interface. In order to avoid exposing the `uWS::Server` loop directly, I plan on adding a function for passing a callback and returning the event handle. One of these functions would exist for each type of event (I need uv_timer_t for performing periodic work, and also uv_idle_t for performing work every iteration). I'm still teaching myself about libuv so I'm not exactly sure on the details.

As I see it, there are 2 alternatives to my design depending on how much you want to expose. First, I could simply make the loop public and let the user handle everything, but then a user could stop the loop without calling close(). The other option is to use the functions I described but return an `int` ID instead of the event handle, and use an internal map. This is a bit cleaner since the user never has to know about libuv, but it adds a small amount of memory for mapping IDs to handles.

**Comment by alexhultman** [comment]
If the server is master, it runs on uv_default_loop() which you can do anything you want with

**Comment by jimmyt857** [comment]
Lol, of course. Like I said, still learning libuv. Thank you.   ;)
