### ISSUE TITLE
Update benchmarks (libwebsockets 2.0 remaining)

### ISSUE THREAD

**Issue by alexhultman** [alexhultman/uWebSockets#117]
@ronkorving You'll get what you wanted :wink:

I just ran the benchmarks, and this is ridiculous because 3 instances of WebSocket++ each running 100% CPU is not able to stress µWS more than 56%, so the difference should probably be something like 40x faster short message throughput, not 20x.

I need to rewrite bench2 for maximum performance so that I can truly stress µWS and give you correct numbers.

**Comment by alexhultman** [comment]
Using a crazily optimized version of bench2 I'm able to reach 100% CPU usage of µWebSockets at 1500 echoes/ms, while ws does 36 echoes/ms (about the same as with the unoptimized bench2).

This puts µWebSockets at 41x as fast as ws. Will publish this benchmark, that only depends on libuv and is cross-platform.

**Comment by alexhultman** [comment]
10k connections:

* 33 echoes/ms using ws
* 455 echoes/ms using uws (Node.js, only swapping require('ws') with require('uws')
* 1030 echoes/ms using uws (Native, C++)

**Comment by ronkorving** [comment]
Sweet!! You just made my... night (it's 2am here :))

**Comment by ronkorving** [comment]
By the way, there's a serious chance we'll use this module on one of the biggest iOS games ever released (give us some time :))

**Comment by alexhultman** [comment]
WebSocket++ does 417 echoes/ms which validates the current claim of 2x (well, it's somewhat over 2x now).

**Comment by alexhultman** [comment]
I need to get an "official" echo server from libwebsockets, because the one I benchmarked is kind of tainted with my own stuff (it's based on node-lws).

**Comment by alexhultman** [comment]
@ronkorving What is this "biggest game ever"? :wink:

**Comment by alexhultman** [comment]
## Benchmarks table (draft)
Implementation | Memory scaling | Connection performance | Short message throughput | Huge message throughput
--- | --- | --- | --- | ---
ws v1.1.0 + binary addons | µWS is **47x** as lightweight | µWS is **18x** as performant | µWS is **33x** as performant | µWS is **2x** as performant
WebSocket++ v0.7.0 | µWS is **63x** as lightweight | µWS is **4x** as performant | µWS is **3x** as performant | µWS is **2x** as performant

This is with the new ws 1.1.0, values are rounded to nearest integer - it's hard to get accurate values, these are just somewhat accurate (performance of ws is extremely varying because the GC kicks in all the time, causing major fluctuations).

**Comment by ronkorving** [comment]
I should have elaborated. Let's just say it's the biggest (world) MMORPG to hit the app store :)
