### ISSUE TITLE
Collaborated Hacker News upvoting plan

### ISSUE THREAD

**Issue by alexhultman** [alexhultman/uWebSockets#118]
How many would be interested in helping out with the initial upvoting of this future post? It is known you need a few initial upvotes to get the ketchup effect going.

I haven't done any posting on HN but this is something I consider. We would have to agree on a specific time for this to work.

**Comment by lpinca** [comment]
lol, I can definetly give your post a couple of upvote.

**Comment by alexhultman** [comment]
Introducing Ultra Scam x2000™, patent pending. Inc.

<img src="https://media0.giphy.com/media/5nFShZWwq3fdm/200_s.gif" />

**Comment by alexhultman** [comment]
But seriously, it is important to uppercut your way to the top when starting from the very bottom, that's why reddit and such is very useful in these cases IMO. People need a slap in the face to understand.

**Comment by kapouer** [comment]
Sure !

**Comment by LordMajestros** [comment]
Lol, sure.

**Comment by SEAPUNK** [comment]
one billion upvotes

![](https://i.imgur.com/AZ57qlJ.jpg)

**Comment by alexhultman** [comment]
<img src="https://cdn.meme.am/instances/400x400/67708458.jpg" />

**Comment by alexhultman** [comment]
#117 
I'm going to rewrite the benchmarking page and supply two new benchmarks for easy validation of all claims made. I think transparency is key in this.

**Comment by alexhultman** [comment]
Check out the new benchmarkings site, it's all very transparent now and I link to it from the front page :)

**Comment by alexhultman** [comment]
Just posted https://news.ycombinator.com/newest

**Comment by lpinca** [comment]
Direct link: https://news.ycombinator.com/item?id=11736938

**Comment by alexhultman** [comment]
You cannot vote through direct links, they remove those.

**Comment by alexhultman** [comment]
Well, that didn't work. Well, what can you do..

**Comment by lpinca** [comment]
It is placed in position 6 so it worked :)

**Comment by alexhultman** [comment]
Yeah I just noticed like 5 minutes ago, I was looking at the "newest" page where it kind of sunk like a stone and fell out of view. Strange behavior. Thanks for the initial bump, now lets see how it is received.
