### ISSUE TITLE
ws.ping method

### ISSUE THREAD

**Issue by silverwind** [alexhultman/uWebSockets#119]
Is [websocket.ping](https://github.com/websockets/ws/blob/master/doc/ws.md#websocketpingdata-options-dontfailwhenclosed) supported in Node.js? I'm getting `TypeError: ws.ping is not a function` after a drop-in replacement of `ws`.

**Comment by alexhultman** [comment]
This will be added in a while. Should be a quick fix. Thanks for reporting this.

**Comment by alexhultman** [comment]
I assume you also want the 'pong' event?

**Comment by silverwind** [comment]
`pong` isn't particulary useful on a server, as web clients don't expose a ´ping´ method, so it's not particularily needed in my case where I just want to make sure the socket stays open through proxies with short timeouts.

**Comment by alexhultman** [comment]
I need to think about this for a while. It can be solved easily, but this solution would be very naive and wasteful. The real question here is why a user would ever care about manually sending pings? The best solution would in my opinion be to let the server library do that under the hood in the most efficient way.

If you let the user manually send pings using the ws.ping function you unlock a bunch of incredibly unnecessary problems that could be avoided if the server did this under the hood. You still need to handle the 'pong' event in some way and you need a timer somewhere.

If I could make the server send pings itself I could optimize this a lot more than if the user controls them. If the user controls them I need one timer per socket, but if the server would just send pings to all sockets itself at given intervals only one timer would be needed.

**Comment by LordMajestros** [comment]
This may break socket.io which has it's own ping pong implementation.

**Comment by alexhultman** [comment]
You would turn it on via an option.

**Comment by alexhultman** [comment]
Anyways - I'm thinking about this, I'm considering having like groups of sockets sharing one timer or having one timer with a queue or just having one timer per socket. It depends on how big the timer is. I need to somehow track time from the ping to the pong.

**Comment by LordMajestros** [comment]
That would work you'd also have to optimise broadcasts (the pings will be broadcasts right?) You still have to track and disconnect dead sockets individually though.

**Comment by LordMajestros** [comment]
Also most browsers don't support ping/pong(last I checked) so a client library usually implements this.

**Comment by alexhultman** [comment]
@silverwind How would you like an option 'pingInterval' instead? Setting this to anything over 0 would make the library manage pings/pongs/disconnections automatically in a more efficient way. I don't know what to do with the ws.ping function - IMO that function is a design flaw, just like most of the ws interface is.

**Comment by silverwind** [comment]
> How would you like an option 'pingInterval' instead

That would be enough for my case. Currently, I [naively ping](https://github.com/silverwind/droppy/blob/d6b0a62a9d5ba8c5cbd2df0847171d908cd2f42a/server/server.js#L93-L99) all known active sockets on a timer, if you can implement this more efficiently in your library, I'm all for it.

**Comment by alexhultman** [comment]
So you ping but you don't listen for the 'pong' event? How does ws determine a connection broken then? If you have one timer and one loop and you call ping in the loop and start the timer then that's a good solution but I don't know how calling ping without listening for 'pong' is helping you. This seems ultra strange. If this really works for you then it means ws is starting a timer for every socket which is just mindblowingly retarded.

**Comment by alexhultman** [comment]
So my point is - a good solution would be something like this:

* For all sockets, call socket.ping, mark the socket in some way
* Start a timer of, say, 120s
* On 'pong' unmark the socket somehow
* When timer times out, close all sockets that are marked

Where a bad solution would be something like:

* For all sockets, call socket.ping & start a timer for this socket
* On 'pong' abort this sockets timer
* On a sockets timer timeout, close this socket

Simply because it makes use of one timer, vs millions of timers.

**Comment by silverwind** [comment]
> I don't know how calling ping without listening for 'pong' is helping you

The issue I'm trying to solve with it is that a reverse proxy like nginx before node has a timeout ([60s by default](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout)) after which it closes any socket it deems inactive. I send pings only to keep that timeout from ever being reached, I don't particularily care if I get a pong or not. If the connection drops through other means, the client will do a reconnect anyways.

Here's another decription of the issue:

> WebSockets are still affected by proxy_read_timeout which defaults to 60 seconds. This means that if you have an application using WebSockets but not sending any data more than once per 60 seconds you either need to increase the timeout or implement a ping message to keep the connection alive. The ping solution has the added benefit of discovering if the connection was closed unexpectedly.

**Comment by alexhultman** [comment]
Ah. So most probably ws is not starting a timer, you need to listen to 'pong' if you care about timeouts. Well, then this problem becomes easier. I think the latest commit should solve this then, I should also add the 'pong' event so that people who are using pings / pongs to determine disconnection can use them for that.

**Comment by silverwind** [comment]
> I should also add the 'pong' event so that people who are using pings / pongs to determine disconnection can use them for that.

Yeah, that'd be the minimal requirement to make it possible for the server to check which clients are still alive.

Regarding my proxy issue: I'd have preferred to send the pings on the client so I can avoid the timer on the server, but alas, it's not implemented in browsers.

**Comment by lpinca** [comment]
> Regarding my proxy issue: I'd have preferred to send the pings on the client so I can avoid the timer on the server, but alas, it's not implemented in browsers.

Can't you send a dummy message? Why does it have to be a ping frame?

**Comment by lpinca** [comment]
AFAIK ws has no timers but implements the ping/pong methods (and their respective events) to send the ping/pong frames as they are part of the protocol specification.
A low level WebSocket library like this should not handle timeouts imho.

**Comment by silverwind** [comment]
> Can't you send a dummy message? Why does it have to be a ping frame?

Yeah, dummy messages look to be the only way to have browser-initiated keepalive.

>  A low level WebSocket library like this should not handle timeouts imho.

Yeah that's probably the way to go. `ws.ping`/`ws.pong` to just put those frames on the wire, and the corresponding events when such frames are received should be enough.

**Comment by alexhultman** [comment]
ws.ping will be available in next release, will do this release in maybe a week or so.
