### ISSUE TITLE
Correct Base64 algorithm ?

### ISSUE THREAD

**Issue by xtuc** [alexhultman/uWebSockets#123]
I'm not an expert, feel free to correct me.

According to the [Wikipedia doc](https://en.wikipedia.org/wiki/Base64#Padding):
> The '==' sequence indicates that the last group contained only one byte, and '=' indicates that it contained two bytes

In your implementation (see [uWS.cpp](https://github.com/alexhultman/uWebSockets/blob/master/src/uWS.cpp#L252-L265)) you are adding systematically one equals at the end of the generated string. While it should be based on the number of bytes in the last group.

**Comment by alexhultman** [comment]
The size of the input (28 bytes) is fix and therefore the output '=' is fix. This base64 is only valid for 28 byte input and 24 byte output.

**Comment by alexhultman** [comment]
I've created about 500 million connections throughout the testing / development process and it has never been wrong.

**Comment by xtuc** [comment]
This restriction comes from the `SHA_DIGEST_LENGTH` constants from the OpenSSL library, right ?

**Comment by alexhultman** [comment]
Maybe the input is 20 bytes, I don't have this in my head but yeah the macro is the size of the input.

**Comment by xtuc** [comment]
`SHA_DIGEST_LENGTH == 20 bytes` is written in the [documentation](https://www.openssl.org/docs/manmaster/crypto/sha.html).

This value shouldn't change so much over time.
