### ISSUE TITLE
Assign in if

### ISSUE THREAD

**Issue by cagdasc** [alexhultman/uWebSockets#124]
Maybe it can be problem uWS.cpp line 90 `if ((nextMessage = head->nextMessage)) {`. There is a assign.

**Comment by LordMajestros** [comment]
It is not a mistake. It is equivalent to 
```
if (head->nextMessage) { //head->nextMessage is not null
    nextMessage = head->nextMessage;
    ...
}
```

**Comment by alexhultman** [comment]
Assignment in condition is marked with extra parentheses and is a known "C pattern".
