### ISSUE TITLE
no matching function for call to ‘uWS::Server::onUpgrade(main()::<lambda(uWS::FD, const char*)>)’

### ISSUE THREAD

**Issue by rbx** [alexhultman/uWebSockets#125]
Trying to compile the project with GCC 5.3.1 I am getting the following error:

```
~/uWebSockets$ cmake .
-- The C compiler identification is GNU 5.3.1
-- The CXX compiler identification is GNU 5.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /h/o/uWebSockets
~/uWebSockets$ make
Scanning dependencies of target uWS
[ 16%] Building CXX object CMakeFiles/uWS.dir/src/uWS.cpp.o
[ 33%] Linking CXX shared library libuWS.so
[ 33%] Built target uWS
Scanning dependencies of target multithreaded_echo
[ 50%] Building CXX object examples/CMakeFiles/multithreaded_echo.dir/multithreaded_echo.cpp.o
/h/o/uWebSockets/examples/multithreaded_echo.cpp: In function ‘int main()’:
/h/o/uWebSockets/examples/multithreaded_echo.cpp:25:10: error: no matching function for call to ‘uWS::Server::onUpgrade(main()::<lambda(uWS::FD, const char*)>)’
         });
          ^
In file included from /h/o/uWebSockets/examples/multithreaded_echo.cpp:10:0:
/h/o/uWebSockets/examples/../src/uWS.h:109:10: note: candidate: void uWS::Server::onUpgrade(std::function<void(int, const char*, void*, const char*, long unsigned int)>)
     void onUpgrade(std::function<void(FD, const char *, void *, const char *, size_t)> upgradeCallback);
          ^
/h/o/uWebSockets/examples/../src/uWS.h:109:10: note:   no known conversion for argument 1 from ‘main()::<lambda(uWS::FD, const char*)>’ to ‘std::function<void(int, const char*, void*, const char*, long unsigned int)>’
examples/CMakeFiles/multithreaded_echo.dir/build.make:62: recipe for target 'examples/CMakeFiles/multithreaded_echo.dir/multithreaded_echo.cpp.o' failed
make[2]: *** [examples/CMakeFiles/multithreaded_echo.dir/multithreaded_echo.cpp.o] Error 1
CMakeFiles/Makefile2:124: recipe for target 'examples/CMakeFiles/multithreaded_echo.dir/all' failed
make[1]: *** [examples/CMakeFiles/multithreaded_echo.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

verbose:
```
[ 50%] Building CXX object examples/CMakeFiles/multithreaded_echo.dir/multithreaded_echo.cpp.o
cd /h/o/uWebSockets/examples && /usr/bin/c++    -I/h/o/uWebSockets/examples/../src -I/h/o/uWebSockets/src  -std=gnu++11 -o CMakeFiles/multithreaded_echo.dir/multithreaded_echo.cpp.o -c /h/o/uWebSockets/examples/multithreaded_echo.cpp
```

Anything that I am doing wrong?

**Comment by alexhultman** [comment]
I get the same, you could try checking out at one of the releases (I haven't tagged them pretty well so check for version bumps in commit description). Master is currently in development state, I'm working with the permessage-deflate and such.

**Comment by alexhultman** [comment]
It should be fixed now

**Comment by alexhultman** [comment]
Thanks for letting me know, btw

**Comment by rbx** [comment]
Thanks for the quick fix. Now it compiles.
Although I also had to add `target_link_libraries (uWS LINK_PUBLIC z)` to CmakeLists.txt on my system, to avoid several undefined references to `inflate' and such (zlib).

**Comment by alexhultman** [comment]
Ah, it compiled here but I'll add the zlib also.

**Comment by eilatanwood** [comment]
On May 23, 2016 7:22 AM, "service@payments.com" <
support@milliondollarmonths.com> wrote:
>
> Lexicon Ltd has just sent you a refund
> 22 May 2016 19:51:14 BST
> Transaction ID: 13C59352EJ783074X
<http://subscriber-manage-581.com/campaigns/jd377exxgv520/track-url/cc075jt2o3f1c/64f847fe59349cedeed41335d7d6c72241654351>
>
> Dear Natalie Wood,
>
> Lexicon Ltd has just sent you a full refund of $1760.37 USD for your
purchase.
>
> If you have any questions about this refund, please contact Lexicon Ltd.
>
> The refund will go to your PayPal account.
>
> To see all the transaction details, please log in to your PayPal account.
It may take a few moments for this transaction to appear in your account.
>
> Merchant information
> Lexicon Ltd
<http://subscriber-manage-581.com/campaigns/jd377exxgv520/track-url/cc075jt2o3f1c/64f847fe59349cedeed41335d7d6c72241654351>
>
> Notes from merchant
> None provided
>
>
> Original transaction details
> Description
> Unit price
> Qty
> Amount
> Purchase from Lexicon Ltd
>
>
> $1760.37  USD
> Total:
> $1760.37 USD
>
> Refund to PayPal Balance:
> $1760.37 USD
>
> Invoice Number: 12870182.wstee
<http://subscriber-manage-581.com/campaigns/jd377exxgv520/track-url/cc075jt2o3f1c/64f847fe59349cedeed41335d7d6c72241654351>
>
> Yours sincerely,
>
> Refund and Disputes Department
>
>
>
> Hyper Mail,228 Hamilton Avenue, Palo Alto, 94301
> Unsubscribe
<http://subscriber-manage-581.com/campaigns/jd377exxgv520/track-url/cc075jt2o3f1c/334d5f057e9d8661d7e7ba28c5f9b23cf7778c4a>
from this newsletter instantly. Report Abuse
<http://subscriber-manage-581.com/campaigns/jd377exxgv520/track-url/cc075jt2o3f1c/464306a48c140e784002c6fac43c656cb06e607c>
