### ISSUE TITLE
Is it possible / planned to use this client side?

### ISSUE THREAD

**Issue by Alan01252** [alexhultman/uWebSockets#126]
Hi,

Apologies if this is a stupid question but is it possible to use this client side too?

We run socket.io-client on a raspberry pi, and do a lot of sending from it, it would be great to run this version of the engine client side as the performance benefits would really benefit the limited resources of the pi.

I had a look through the code, but got completely lost about how this would work, I don't *think* the socket.io-client library supports changing the engine as yet, so would have to do something nasty to get it  to work..

Thank you!

Alan

**Comment by SEAPUNK** [comment]
Duplicate of #104?

**Comment by alexhultman** [comment]
Currently there is no client support planned, but it should be possible to add. This won't happen as a priority though - I want to target on the server first of all.

**Comment by Alan01252** [comment]
Thank you for your swift responses!

This is indeed a duplicate but hopefully gives a different use case and shows why it would be very handy for some people :)

Thanks again!
