### ISSUE TITLE
Unable to install from NPM / Source

### ISSUE THREAD

**Issue by kinsi55** [alexhultman/uWebSockets#128]
Hai there.

Im trying to give µWS a go but am struggling to get it installed. I've already compiled >= cmake 3, and compiled libuv 1.0.0 without a problem.

Installing trough npm, and compiling from git yields to the same compiler error for me now though:

```
In file included from ../src/uWS.cpp:1:0:
../src/uWS.h: In constructor ‘uWS::Server::Server(int, bool, std::string)’:
../src/uWS.h:87:9: warning: ‘uWS::Server::port’ will be initialized after [-Wreorder]
../src/uWS.h:86:22: warning:   ‘bool uWS::Server::master’ [-Wreorder]
../src/uWS.cpp:163:1: warning:   when initialized here [-Wreorder]
../src/uWS.cpp: In lambda function:
../src/uWS.cpp:213:52: error: ‘this’ was not captured for this lambda function
../src/uWS.cpp: In lambda function:
../src/uWS.cpp:217:54: error: ‘this’ was not captured for this lambda function
../src/uWS.cpp: In lambda function:
../src/uWS.cpp:633:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
make: *** [Release/obj.target/uws/src/uWS.o] Error 1
```

Am i doing something really obvious wrong here?

**Comment by alexhultman** [comment]
If you want the Node.js addon you simply hit "npm install uws". This install never fails and does not print any output (except for to build_log.txt). Did you find this output in build_log.txt? Are you on Windows?

**Comment by kinsi55** [comment]
Totally forgot to mention that, I'm sorry. Yes this is from the build log which I checked because after installing it with npm and requiring it in my code I was greeted with a message that uws failed to compile and there's no precompiled version for my OS. I am on Linux, Debian to be exact.

**Comment by alexhultman** [comment]
What major version of Node? Even if the compilation fails it should fallback to a pre compiled binary.

**Comment by kinsi55** [comment]
Currently running 5.1.0

**Comment by alexhultman** [comment]
Well this should not happen. There are pre-built binaries for 64-bit Linux with Node 5, so in worst case it should just use that binary. Are you on 64-bit? What version of GCC/Clang? What version of NPM?

**Comment by kinsi55** [comment]
Yes I am on 64 bit. My npm version is 3.3.12, gcc is 4.7.2, cmake is at 3.2.2. Thank you

**Comment by alexhultman** [comment]
Well I just installed uws 0.4.1 on my secondary computer with "npm install uws" and both compilation and fallback works. I guess the problem in this could be your ancient GCC version causing the compilation to fail and also the pre-compiled binary to not be compatible.

This lib is written in C++11, which became fully supported in GCC 4.8. I cannot see anything making sense at this error report, "this" is not even used in the lambda at all so reporting an issue with the capture of "this" is not correct as far as what I can see.

How does your node_modules/uws folder look like? Mine looks like this:

```
[alexhultman@localhost uws]$ ls
binding.gyp    logo.png      uws_darwin_46.node  uws_linux_46.node
build          package.json  uws_darwin_47.node  uws_linux_47.node
build_log.txt  README.md     uws_darwin_48.node  uws_linux_48.node
LICENSE        src           uws.js
```

What I'm wondering about is if you have the "uws_linux_47.node" file or not (that would be the pre-compiled binary for Node.js 5.x).

**Comment by kinsi55** [comment]
The file indeed does exist

... 
ls node_modules/uws/
binding.gyp    logo.png      uws_darwin_46.node  uws_linux_46.node
build          package.json  uws_darwin_47.node  uws_linux_47.node
build_log.txt  README.md     uws_darwin_48.node  uws_linux_48.node
LICENSE        src           uws.js
... 

I will try upgrading my gcc and give it another go.

**Comment by kinsi55** [comment]
I have gcc 4.9 now, compile and install worked (now via npm too). The only thing I had to change from the docs is doing `io.engine.ws = new(require('uws')).Server({` instead of `io.engine.ws = new require('uws').Server({` as it would otherwise tell me that class constructors cannot be called without new.

Works now though, sorry for the inconveniences and thank you for your time!

**Comment by alexhultman** [comment]
Nice to hear. Don't worry about it, I find these kinds of reports about how it behaves on different set-ups useful. I had no idea it was broken on GCC 4.7 and prior versions - that's good to know :wink: If the docs about Socket.IO is wrong I can update it, I got this snippet from one of the other Socket.IO users and just copy-pasted it.

**Comment by kinsi55** [comment]
I found the issue. You might want to consider `.log`ing the error that comes from the try catch, as the issue in my case simply was a missing (outdated) libc6.

**Comment by alexhultman** [comment]
What is the reopening about then?

**Comment by kinsi55** [comment]
Im sorry im on my phone and must have hit the wrong button.
