### ISSUE TITLE
Difference in memory usage with --gc_global

### ISSUE THREAD

**Issue by alexhultman** [alexhultman/uWebSockets#129]
Longstanding issue. I need someone who is an absolute expert at JavaScript who can help me optimize the JavaScript code. It consumes extreme amounts of memory per socket compared to the native server. There is absolutely no reason for the binding to bloat the server with 95% of its memory usage alone (this is purely insane).

If you want to point me in the right direction on how to minimize memory usage, please do.

**Comment by alexhultman** [comment]
I guess tools like https://github.com/bnoordhuis/node-heapdump could be useful. I need to understand in a deterministic way what consumes memory in JS and how to reliably measure memory usage of objects in different contexts.

**Comment by alexhultman** [comment]
This commit: 5fdf6119a5d305303fbe54848a288fa0d544e787 adds options uwsHttp, noUpgradeReq.

By passing `uwsHttp: true, noUpgradeReq: true` as options to the server constructor the memory issue can be seen very clearly. Using uwsHttp, the server process consumes 260mb of memory per 450k connections, while `uwsHttp: false, noUpgradeReq: true` requires 544 mb of memory per 450k connections.

Heapdumps show almost identical memory usage, sockets require identical amounts of memory yet still the server process grows at almost double the rate when not using uwsHttp.

**Comment by alexhultman** [comment]
So I think I know why this is happening now, at least it makes sense.

The `uwsHttp` option makes use of the built-in uws HTTP server (native code, does not spill memory to the GC). In other cases, the Node.js HTTP server is used (JS code, makes heavy use of GC, spills destroyed sockets to be reclaimed by the GC).

The HTTP server is only used to receive the HTTP upgrade header, so the memory usage should be identical after this (which is the case according to heapdumps). I'm pretty sure the heapdumps only show reachable memory, that is, it doesn't show memory that is to be reclaimed by the GC (this would make no sense to show, I guess).

By adding the option `--gc_global` to node, the memory usage is reduced from ~550mb to 290 - 320mb. This is a lot more reasonable, even if it still is not as good as when using the `uwsHttp` option (but pretty damn close).

It seems, the GC sucks more than I thought. The reason for the `uwsHttp` option being more efficient in memory seems to be simply because it never really makes any use of the GC at all.

**Comment by lpinca** [comment]
Maybe things will be a little better with the next node version in the 6.x line. See http://v8project.blogspot.it/2016/04/jank-busters-part-two-orinoco.html

**Comment by alexhultman** [comment]
**rant**

Out of manual memory management, RAII, ARC and GC - the GC is by far the most retarded solution as it is the only solution that really harms *both* memory footprint and performance.

Since the GC is slow as a snail, Google need to hide this by making it worse at collecting memory - which of course is the very purpose of the GC. So you gain performance but lose in memory footprint. While turning on better GC options you lose in performance and gain in memory footprint. You cannot get both good performance and good memory footprint like you can in the three other solutions (which are all very good solutions).

The fact that I'm trying to get by using Hello Kitty tools is just a joke in itself. Memory management in JS is just terribly broken and impossible to work with. Claiming JS actually works for creating scalable servers is just the biggest lie ever told.

JavaScript developers drive to work like this:
<img src="http://www.pinkorblue.se/out/pictures/generated/product/4/900_900_80/a006497_004.jpg" />

**Comment by lpinca** [comment]
Please don't offend my big bobby car.

**Comment by alexhultman** [comment]
*mic drop*

**Comment by alexhultman** [comment]
I truly hate JavaScript, have I ever told you this? :wink:

**Comment by lpinca** [comment]
Not directly but having read some of your comments/posts it doesn't surprise me 😄.

**Comment by alexhultman** [comment]
:smile: I can still be wrong, but it seems unlikely now with the same behavior with vanilla JS. I guess this is just how it is supposed to work. We have to see how it behaves in that new V8 GC you linked.

**Comment by lpinca** [comment]
> I guess this is just how it is supposed to work.

Yes I think so.

**Comment by alexhultman** [comment]
Note to self:

```javascript
'use strict';

const http = require('http');
const EventEmitter = require('events');
var socketArray = [];

class Socket {
    constructor(nativeSocket) {
        this.nativeSocket = nativeSocket;
    }
}

class Server {
    constructor(options, callback) {
        this.httpServer = http.createServer((request, response) => {
            response.destroy();
        });

        this.httpServer.on('upgrade', (request, socket, head) => {
            socket.on('close', (error) => {
                socketArray.push(new Socket(123.34345));
            });

            socket.write('\r\n\r\n', () => {
                socket.destroy();
            });
        });

        this.httpServer.listen(options.port, callback);
    }
}

const wss = new Server({ port: 3000 });
```

61mb vs 133mb

**Comment by lpinca** [comment]
What changed? The EventEmitter? How can it double the memory usage?

**Comment by alexhultman** [comment]
I removed some fields from the Socket object and removed setting the onmessage so there is more things removed. Now it is really slim and still I get the same 2x memory difference (but at smaller scale).

**Comment by lpinca** [comment]
ah correct, I guess `onmessage` kept `ws` alive.

**Comment by alexhultman** [comment]
Yes but I add it to a vector so that is is alive. If I remove that it keeps at ~50mb memory constant (which shows that socket.destroy seems to work).

**Comment by lpinca** [comment]
Gotcha.

**Comment by alexhultman** [comment]
Yeah so it is the `socketArray.push(new Socket(123.34345));` that makes a huge difference. Without it it keeps constant no matter if I make millions of connections or 100k. So whatever socket.destroy() leaves behind, the GC is able to find and delete with the default settings. But things diverge when adding to socketArray. Very strange, this code is so minimal.
