### ISSUE TITLE
cannot release server after close

### ISSUE THREAD

**Issue by joyousrabbit** [alexhultman/uWebSockets#134]
Hello alex,

This is very great work and your code is perfect. Only one issue, 

I took server.run() in a detached thread, then I server.close() from another thread (the main thread). 
The server is correctly closed because the following connections are lost. 

But, the detached thread is still always blocked by server.run() and keep the thread alive, even after it is closed.

How can we pass from server.run() after calling server.close() to finish the detached thread?

Hope your reply and many thanks.

**Comment by alexhultman** [comment]
Hi,

This should work, I do this all the time. How are you setting the master boolean?

```c++
Server(port, master, ...)
```

Master should be false for server not running on the main thread, that will make server.close and server.upgrade thread safe.

**Comment by alexhultman** [comment]
https://github.com/alexhultman/uWebSockets/blob/master/main.cpp

Here you see I have two servers, one running on the main thread and one running on a separate one. When the number of connections are 2, I close both servers (worker thread closes its own server and the one on the main thread). They both return and the threads both terminate.

**Comment by joyousrabbit** [comment]
@alexhultman , Thank you for reply. It finished as expected after change master from true to false.

**Comment by alexhultman** [comment]
Nice :) The multithreaded design is not set in stone but I try and keep it simple: servers on main thead are masters and servers on separate threads are not masters, pretty much.
