### ISSUE TITLE
Spikes

### ISSUE THREAD

**Issue by rezoner** [alexhultman/uWebSockets#137]
A lot of messages arrive at the same time despite being send in constant interval (20 per second).

Number to the left is a tick number - number to the right is the count of the messages received in this very animation frame.

This is not the case when switching back to websocket/ws - the result is that despite huge CPU gain (idle for 70% of time) the game behaves like if it was updated by the number of accumulated frames times slower.

![image](https://cloud.githubusercontent.com/assets/1395544/15754451/7f527d0c-28f8-11e6-811e-1e0650694639.png)

Below - same screenshot from websocket/ws

![image](https://cloud.githubusercontent.com/assets/1395544/15754743/f75083fc-28f9-11e6-988a-5548bf349f84.png)

**Comment by alexhultman** [comment]
This is according to design. If you receive 10 frames, you will get 10 messages emitted. If you have problems with this you need to solve it somehow, this shouldn't affect your networking code.

**Comment by alexhultman** [comment]
If you expect to get one message per "tick" then you need to call process.nextTick in your callback and queue up a closure with the copy of the message for later traversal. This is ofc massively coslty in performance but it should even out these "spikes".

**Comment by danzel** [comment]
@alexhultman I think you may have misunderstood. What @rezoner means by tick is the rendering frame number.

Using websocket/ws messages are being received usually 3 rendering frames apart (this is ~20 times a second) which is the rate they are being sent at.

When using uWebSockets, even though the messages are being sent at a 1/20th of a second rate they are getting grouped up so multiple packets get received by the client at the same time with a larger gap between them (like maybe uWebSocket is grouping them for performance instead of sending them immediately?)

I've only had a brief look through, but I don't see anywhere in the code enabling TCP_NODELAY, which may cause this?
ref https://en.wikipedia.org/wiki/Nagle%27s_algorithm

**Comment by alexhultman** [comment]
Ah.

You have any code to reproduce it separate from the game? You could probably display real time at every message event and have a simple timer send at equal periods.

Tell me more about what side is sending etc, or just provide some code

**Comment by rezoner** [comment]
@alexhultman 

Live (open console):

WS - http://rezoner.net/temp/ws/
UWS - http://rezoner.net/temp/uws/

Source:
https://gist.github.com/rezoner/c28239f4932fe6ab46b666b5a4a229d9

Note: You will not have the spikes when running both server and client on localhost.

**Comment by alexhultman** [comment]
Nice code. So if I set this up in a local network it should trigger?

**Comment by rezoner** [comment]
I guess you need at least some distance between client and server so the latency is greater than 0.
Running that on localhost will not give you spikes.

**Comment by alexhultman** [comment]
I don't know what ws does and I haven't run the code but my best bet would be for you to turn on TCP_NODELAY on this socket if you need one send to be received as one package. When you call socket.send this is pretty much a wrapper of Unix send straight up and I don't control the behavior of the TCP stack.

**Comment by alexhultman** [comment]
There is really no guarantee of how and when packages will be delivered, the TCP protocol is just a stream in which you put stuff and it comes out the other end in any possible segmentation / delay. So yeah, TCP_NODELAY would probably solve your problem. I could add the ability to set this on and off.

**Comment by alexhultman** [comment]
https://nodejs.org/api/net.html#net_socket_setnodelay_nodelay

Does ws use this function?

**Comment by alexhultman** [comment]
https://github.com/websockets/ws/search?utf8=✓&q=setnodelay

They seem to set noDelay yes, so this is most probably the problem.

**Comment by alexhultman** [comment]
@rezoner could you try and modify uws.js to setNoDelay(true) on the socket in handleUpgrade? That should translate all the way into the lib.

**Comment by rezoner** [comment]
@alexhultman 

**Jackpot**

![image](https://cloud.githubusercontent.com/assets/1395544/15804431/08354d28-2b08-11e6-8d52-c2e0e9da6ae1.png)

![image](https://cloud.githubusercontent.com/assets/1395544/15804434/13e01d60-2b08-11e6-9889-2ec0821a910d.png)

**Comment by rezoner** [comment]
And with that I am able to at least double the number of players per server.

![image](https://cloud.githubusercontent.com/assets/1395544/15804511/83898202-2b0b-11e6-8d16-5e199f746d97.png)

**Comment by alexhultman** [comment]
<img src="https://lygsbtd.files.wordpress.com/2016/01/hippies-grow-pot.jpg?w=490&h=338" />

**Comment by alexhultman** [comment]
So maybe we could make this optional with a server setting noDelay: boolean? Do you want to PR this?

**Comment by rezoner** [comment]
@alexhultman I am letting you to decide whether it should default to true or be configurable - I am happy either way. It's enabled by default in WS - but you have to think of CPU consequences. Imho it should be true by default as it won't be a matter for 90% of projects - and if someone is in the latter 10% he will surely be in need for a very specific performance tricks and gonna dig that up in docs.

> Do you want to PR this?

Nah, I've done nothing just copy-pasted your own findings.

**Comment by alexhultman** [comment]
I added an option noDelay that is false by default (TCP default, I don't think one should mess with TCP defaults by default). Set this to true in cases such as games, but not in cases such as file transfer, chat, etc.

**Comment by Dillybob92** [comment]
I am curious... how exactly does uWebSockets push out more than double the performance compared to WS? What is it exactly doing behind the scenes that makes it so much faster? I want to switch too... lol

**Comment by alexhultman** [comment]
Ws is one pile of garbage, there is no competition with garbage.

**Comment by alexhultman** [comment]
@Dillybob92 Okay sorry for me previous post. But really, in all honestly, ws is truly terrible. If you compare ws against WebSocket++ or libwebsockets you will see that ws is in fact really, really, really slow. Most users report about 2x performance increase when switching from ws, but you should theoretically be able to achieve a larger difference if WebSockets is your bottleneck. Most projects have other bottlenecks kicking in though.

**Comment by Dillybob92** [comment]
@alexhultman That's fine! I am glad I found this thread though, because I am using ws and spent a lot of time within it, but if the performance here is drastically better.. I am switching too. Is it most likely because this is a native binding solution? Or is it just designed differently?

**Comment by alexhultman** [comment]
@Dillybob92 Make sure to report any issues you find if you swap, there are quite a few functions missing right now.
