### ISSUE TITLE
socketServer.clients is not exposed? 

### ISSUE THREAD

**Issue by samsonradu** [alexhultman/uWebSockets#140]
How can I iterate over the connected clients? 

Something like: 
https://github.com/websockets/ws#server-sending-broadcast-data

**Comment by LordMajestros** [comment]
You can send a broadcast using the broadcast method. It hasn't been optimized yet but it does exactly that.
https://github.com/alexhultman/uWebSockets/blob/master/nodejs/dist/uws.js#L335

**Comment by samsonradu** [comment]
I'm aware of that but I need to do some pre-checks eg:

for (var i in this.clients) 
    if (this.clients[i]._channel == channel) 
        this.clients[i].send(data, opts);
}

**Comment by LordMajestros** [comment]
I currently just put the socket objects in sets in onConnection or onMessage and loop over the set.
That way I don't have to loop over every socket to broadcast to a subset.
A socketServer.clients method would be more convenient I suppose.

**Comment by alexhultman** [comment]
There is no JavaScript vector of sockets, you have to build that yourself if you need one. In any case, you shouldn't have to loop over all vectors doing checks, just sort the sockets in a vector of vector of sockets.
