### ISSUE TITLE
Add readyState getter function to Socket

### ISSUE THREAD

**Issue by rezoner** [alexhultman/uWebSockets#145]
Sometimes (very rare) this line triggers the error:
```
var ip = socket._socket.remoteAddress;
```

![image](https://cloud.githubusercontent.com/assets/1395544/15927635/18fd154e-2e43-11e6-9b28-9926af1bcfec.png)

I am using uws@0.4.1

**Comment by alexhultman** [comment]
You are probably trying to read the remoteAddress of a closed socket, nativeServer is set to null after closing the socket.

**Comment by rezoner** [comment]
What's the shortest way to check if the socket is in closing state?

**Comment by alexhultman** [comment]
nativeSocket is null when closing/closed. You could PR a function to Socket called readyState that returns the correct state: https://github.com/websockets/ws/blob/master/doc/ws.md#websocketreadystate

Is it possible to add these states OPEN / CLOSED as constants to Socket without requiring any memory?

**Comment by alexhultman** [comment]
Ah, I guess one could have a (getter) function called CLOSED that returns an integer - that way there is no addition of size to the Socket object.

**Comment by lpinca** [comment]
I think you can also add a property to the socket (`readyState` for example) and update it accordingly:
```js
socket.readyState = Socket.CLOSED;
```
where `Socket.CLOSED` is a static property of the `Socket` class with an integer value.
The memory overhead should be negligible.

**Comment by alexhultman** [comment]
readyState is just going to be the same as nativeSocket != null ? OPEN : CLOSED so it can be made a getter function instead.

**Comment by lpinca** [comment]
Your call, I don't mind :)

**Comment by alexhultman** [comment]
0d9527903b445e83ff0ff1a1595dfc169ac1f20d should probably work.
