### ISSUE TITLE
[Request] -- Host Option

### ISSUE THREAD

**Issue by Dillybob92** [alexhultman/uWebSockets#147]
Hey! I'm coming from the old ws repo since I heard all the goodies about this and have been testing it. Performance is insane.

One thing I've noticed though, is there is no host option available as from the old ws, for example:
`var wss = new WebSocketServer({ host: '127.0.0.1', port: 9300 });`

This is useful as it doesn't expose the port, only to 127.0.01 (locally). in uWebSockets (this module), it exposes it to the outside -- You can use iptables to fix this, but meh. I think if there was an added `host` option, similar to `ws`, it would be great!

This is useful when sticking the uws server behind a reverse proxy as well!

**Comment by alexhultman** [comment]
Sure

**Comment by alexhultman** [comment]
So basically this is just about taking the host option and passing it to listen: https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback. This is up for grabs.

**Comment by alexhultman** [comment]
I guess this solves it: 0ab94acee26967260309e60663a5d890d7d7c7dd
