### ISSUE TITLE
LMAO

### ISSUE THREAD

**Issue by Dillybob92** [alexhultman/uWebSockets#150]
>  where `head` is of type `struct Message` ? Is this some kind of performance trick ?... Otherwise it looks kind of suspicious.. [source](https://news.ycombinator.com/item?id=11737660)

Alex, you better watch out. We got a virus in our code.. LOL what a joke that site is

**Comment by Dillybob92** [comment]
Also.

This guy is a moron:

> There's no need to resort to insults in-reply to questions or criticisms.
It's a valid question (that i think you did answer, but not very well). Dropping to very unsafe "lower levels" should only be done when absolutely necessary as a single mistake here could cause massive security issues

@alexhultman  You never insulted him, saying "get over yourself" is not an ad-hom, and, to be fair the guy you were replying to, said your code looked like "shit", and "suspicious"

**Comment by Dillybob92** [comment]
YN is a SJW cesspool and they become triggered far too easily. Fuck that, I didn't see anything wrong with how you represented yourself, they were talking shit to your code.

**Comment by SEAPUNK** [comment]
Who cares? What happened on YC happened on YC. I doubt Alex wants you to revive whatever drama happened there.

Besides, this thread makes you sound super obnoxious.

**Comment by Dillybob92** [comment]
Who cares? I do. The way they treat open source projects there is horrid and stupid. Mind telling me what I said here that makes me seem "obnoxious"?

**Comment by LordMajestros** [comment]
@Dillybob92 The fact that starting this thread at all was very unnecessary?

**Comment by SEAPUNK** [comment]
Other than you opening this thread with the title "LMAO", and then rambling about hot memes e.g. "SJW cesspool"?

**Comment by Dillybob92** [comment]
It's necessary because Alex doesn't deserve the hate and belittlement he received on YC. I've switched to uWebSockets and have been using the `ws` module for years and finally made the switch. I am running it in production, and the performance has been insane in comparison. And for them to belittle the project and say that the code is "shit", etc is wrong. That's why it's necessary and I wanted to let Alex know that

**Comment by SEAPUNK** [comment]
There is literally no reason to get so upset about people having differing opinions. We like his code, and we use it, isn't that enough?

Regardless, the issue tracker is mostly meant for things like issues with the code. Twitter or other social media are more appropriate for such complaints.

**Comment by LordMajestros** [comment]
@Dillybob92 I'm using his code in production too. Performance is insane. This is not the way to let him know that. Use its, do PRs, etc don't open an issue just to sling mud

**Comment by Dillybob92** [comment]
I'm not really upset, just more sad about why YC treats people like this. But there was no way to contact Alex so I decided to make the issue to get him notified and I closed it. 

@LordMajestros  I deleted my other posts, you're right

**Comment by SEAPUNK** [comment]
> there was no way to contact Alex

Look at his profile, his email is right there.

![](https://i.imgur.com/cx8Hkq3.png)

**Comment by Dillybob92** [comment]
Weird, doesn't show it for me: 
![image](https://cloud.githubusercontent.com/assets/10387670/16002302/c9598d1c-310b-11e6-9bad-b245fe0f0a39.png)

**Comment by SEAPUNK** [comment]
That _is_ weird. Must be one of my Github extensions.

**Comment by SEAPUNK** [comment]
..or not. On my Firefox installation that doesn't come with any addons, I can see his email. Try opening the page in incognito mode.

**Comment by Dillybob92** [comment]
Hmm. It does show on incognito. Probably messed one of my settings, albeit, not sure which one haven't touched my settings in months :D

**Comment by alexhultman** [comment]
lol

**Comment by alexhultman** [comment]
@Dillybob92 I get notifications from this thread, so I read what you wrote already (I want whatever you're on). Yes, these people are assclowns but I don't care about them at all. I also do not care about how people act like Dr. Phil trying to map out my childhood from how I "attack" these people. I don't read Hacker News and I don't care about people who read it or comment there - I just posted to get the well-known traffic.
