### ISSUE TITLE
Some benchmarking results on a $2.99 VPS

### ISSUE THREAD

**Issue by Dillybob92** [alexhultman/uWebSockets#152]
Hey guys, the documentation wasn't kidding when it said this would run laps around ws.

I am testing this on a $2.99 VPS: 
CPU Specs:
model name      : Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
cpu MHz         : 600.021
cache size      : 20480 KB

As you can see, this OpenVZ box is only allocated .600 MHz out of the 2.4. But, it's still a wild horse.
#### Benchmark Code: 
```
var WebSocketServer = require('ws').Server; /* you replace 'ws' with 'uws' */
var wss = new WebSocketServer({
    port: 9300
});

counter = 0;
wss.on('connection', function(ws) {
    ++counter;
    function callback() {
        counter++;
        ws.send('hello')
        setImmediate(callback);
    }
    setImmediate(callback);
    ws.on('message', function(message) {
        //console.log('received: ' + message);
    });
    //ws.send('something');
});

setInterval(function() {
    console.log('Messages Per Second: ' + counter)
    counter = 0;
}, 1000);
```

#### Index.html
```
GISocket = new WebSocket('ws://ip:9300');
```

#### Results with the `ws` module:
```
Messages Per Second: 3609
Messages Per Second: 5025
Messages Per Second: 4950
Messages Per Second: 3662
Messages Per Second: 4700
```
Average msg/s: **4389.2**

#### Results with the `uws` module:

```
Messages Per Second: 79587
Messages Per Second: 73756
Messages Per Second: 74283
Messages Per Second: 62016
Messages Per Second: 69425
```
Average msg/s: **71,813**

Proof: https://i.gyazo.com/8d8e6cc147eba37f839c03f92ddf0138.png

This is with only text, but I assume would binary be even faster? I find it kind of funny that uws makes chrome crash because of such the high message rate, haha.

**Comment by alexhultman** [comment]
If you feel like it you are very much welcome to spread these results to the ws developers. They are still ignoring the very existence of µWS and still very firmly holding on to their claims **ws: The fastest RFC-6455 WebSocket implementation for Node.js.**. Third party benchmarks are always a good idea to really show the results from different perspectives and different users.

**Comment by ronkorving** [comment]
You could just have some fun with them and make a PR that removes that line from the readme ;) But all kidding aside, I do agree it would be good to mention to them.

**Comment by alexhultman** [comment]
My biggest problem is their project description. If they want to show true sportsmanship they should just rename it to something like "ws: The fast RFC-6455 WebSocket implementation for Node.js.". But they already know this, I personally asked Arnout to change it like 4 months ago and he just censor-blocked me. So yeah, ws developers are real assclowns.

**Comment by Dillybob92** [comment]
I just found out there is a huge memory-leak / bug with `perMessageDeflate` in `ws`. So to be fair, I disabled it by doing `perMessageDeflate:false`, and here are the new results:

```
Messages Per Second: 18304
Messages Per Second: 20532
Messages Per Second: 12339
Messages Per Second: 19391
Messages Per Second: 18932
```

Average msg/s: **17,899**

I tried to submit a bug report, but after submitting it, I got redirected to this screen: 
https://i.sli.mg/RoE8mi.png

**Comment by alexhultman** [comment]
@Dillybob92 So they played the censor-blocking on you too? Man, these clowns really want to hide µWS from ever being found.

**Comment by Dillybob92** [comment]
Yeah, I made the issue on a separate account. I don't understand why they havn't addressed it. The guy that owns wilds.io said he reported it a long time ago as well. I personally think it's a major performance degradation.

**Comment by alexhultman** [comment]
So the new results with perMessageDeflate off on both are about 17 vs 71? That seems more reasonable, but I bet you could get a bigger difference by having a more optimized client - still its a big difference.

**Comment by alexhultman** [comment]
@Dillybob92 I don't get it? What havent they addressed? The bug or the description? And why did they block you? Did they block you just now? Man I love drama :smile:

**Comment by Dillybob92** [comment]
Yeah. The real sad part here is a lot of people use `ws`. And there is no documentationthat tells them about the `perMessageDeflate` performance degradation. No one probably knows how to even disable it. Or nonetheless, a "reason" as to why.  

Yeah, I submitted the bug with the benchmarks with `perMessageDeflate` set to true / false. And it redirected me to say I was blocked. This was after I posted this thread too. Weird.

So, I posted the issue on a new account: https://github.com/websockets/ws/issues/756#issuecomment-226159571

They continue to close it. I give up, whatever. Maybe he is right.

**Comment by alexhultman** [comment]
Lol you specify perMessageDeflate: false. But you still got like 7-8 difference so it's still a huge difference in perf.

**Comment by PokemonAshLovesMyTurkeyAndILikeYouTwo** [comment]
Just referenced it here, lets see what he has to say.

**Comment by alexhultman** [comment]
IMO you got a good response. There is nothing wrong with compression taking longer - you swap CPU for bandwidth.

**Comment by PokemonAshLovesMyTurkeyAndILikeYouTwo** [comment]
Yeah, I was quoting `ws: The fastest RFC-6455 WebSocket implementation for Node.js.` -- as I moved on because @3rd-eden is right. But, the point was as you said, even when it's disabled, the performance is 7-8x slower, it's drastic. It's also enabled by default and I would of never known about its performance degradation until reading [this](http://www.html5gamedevs.com/topic/22593-wildsio-multiplayer-hacknslash/?do=findComment&comment=129752) post. 

The fact that they claims it's the "fastest Websocket Implementation" and has the perMessageDeflate setting enabled is worrying.

**Comment by PokemonAshLovesMyTurkeyAndILikeYouTwo** [comment]
Removed my post, `perMessageDefault` is documented.  I'm getting ahead myself. I'll just stop posting :) lol. In any event, at the end the day, they should indeed change their description.  Thanks for the good drama discussion Alex, and again, thanks for the awesome module!
