### ISSUE TITLE
UNKNOWN TOKEN: 2149 with uws@0.5

### ISSUE THREAD

**Issue by kapouer** [alexhultman/uWebSockets#153]
Hello,
this is logged very often after installation of uws@0.5.1 (of course).

I'm using a server with perMessageDeflate set to false.

Regards,
Jérémy.

**Comment by alexhultman** [comment]
This is some unknown extension token and shouldn't be logged but yeah, it is. So it doesn't do anything but should be silenced in upcoming releases.

**Comment by kapouer** [comment]
Ok, but if perMessageDeflate is set to false, the token shouldn't be parsed ?

**Comment by alexhultman** [comment]
The best would be to skip parsing the extension request if having permessage-deflate disabled yes but currently it gets parsed in any case. Its not an issue, I just forgot to remove that logging.

**Comment by alexhultman** [comment]
This is fixed in 0.6.0
