### ISSUE TITLE
Debian Jessie  `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by Dillybob92** [alexhultman/uWebSockets#155]
Hey guys,

So basically, I re-installed Debian Jessie from a VPS server at OVH.

After `npm install uws`

It all went well, then when I start `node test.js`, I get:

`
        throw new Error('Compilation of µWebSockets has failed and there is no pre-compiled binary ' +
`
So I edited `uws.js` and added `console.log(e)` after that error under the `catch`.

I got:
```
[Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /root/node_modules/uws/uws_linux_47.node)]
```

I did some research, and it seems like from this post http://stackoverflow.com/a/29872049/6176307

I need to re-install `libc6`. So I do `apt-get install libc6`, and then I get:
```
libc6 is already the newest version.
```

Is this a uws issue or a os issue? If not I apologize, I just have no idea, kind of new to linux. But `uws` worked fine under wheezy last week. Maybe Jessie has its own problems

**Comment by SEAPUNK** [comment]
What *is* your libc version? `dpkg -l libc6`

**Comment by Dillybob92** [comment]
@SEAPUNK

```
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libc6:amd64    2.13-38+deb7 amd64        Embedded GNU C Library: Shared li
```

**Comment by SEAPUNK** [comment]
You *barely* miss the requirement goal. Try to install libc6 from one of the unstable repos.

**Comment by Dillybob92** [comment]
Boom, got it SeaPunk, followed [this](http://stackoverflow.com/a/21254623/6176307)

-- This is definitely OS issue, my bad.  :D
