### ISSUE TITLE
Compatilibity with SockJS

### ISSUE THREAD

**Issue by Nazariglez** [alexhultman/uWebSockets#156]
Hello guys! 

Exists there some way to use uws with SockJS lib? 

Server: https://github.com/sockjs/sockjs-node
Client: https://github.com/sockjs/sockjs-client

**Comment by alexhultman** [comment]
I don't understand what SockJS is, but you could also just port your code over to the ws interface. I guess.

**Comment by SEAPUNK** [comment]
SockJS is basically a websocket framework, competitor with socket.io.

**Comment by Nazariglez** [comment]
Thanks @SEAPUNK, I don't have time right now to try to create a new sockjs ws-interface, (I don't know coffescript either), but in near future I want to make some benchmarks with faye vs uws. 

Thanks for your help!

**Comment by alexhultman** [comment]
I never tested Faye (yes I actually fell for the ws marketing) so it would be interesting to see some results. Make sure to use a client that fully stresses the server when testing. This is hard to find so you should probably have multiple separate instances of the client connected.

**Comment by dceejay** [comment]
maybe some variation of https://gist.github.com/danielstjules/71ade40ce7c145c857a6

**Comment by alexhultman** [comment]
@dceejay Why is that simple patch not merged into sockjs? What is the reason not to use ws over Faye? If it really is that simple to avoid all of Faye then they (sockjs) should really look at swapping and then also introduce a similar mechanism as Socket.IO now uses (uws first, ws as fallback).

**Comment by dceejay** [comment]
indeed - all good questions...
