### ISSUE TITLE
ws "pong" compatibility

### ISSUE THREAD

**Issue by mjsherman** [alexhultman/uWebSockets#157]
Both a feature and bug:

Compatibility:
ws emits a "pong" message to application level when a OPCODE_PONG is received.  Current uws does not expose this to the application level.

Bug:
In our application, we currently listen for the "pong" messages and count missed ping/pongs to disconnect clients reasonably quickly when they stop responding to pongs.  Since the pongs aren't emitted, with our current server, we disconnect clients that are still connected/valid.  This causes uws to spam "CLOSING state, Socket::write", and spike to 100% CPU.  Below is a small snippet of what we're doing essentially that causes the spike/spam.

```
setInterval(function() {
    for (var id in allSockets) {
        var socket = allSockets[id];
        socket.unanswered_pings++;
        if (socket.unanswered_pings > 2) {
            socket.close();  // THIS LINE CAUSES SPAM (SEE BELOW)
        } else {
            socket.ping();
        }
    }
}, 10000);

// Elsewhere (in ws this is called, in uws it is not)
socket.on('pong', function() {
    socket.unanswered_pings = 0;
});
```

NOTE: Since pings are never answered (at the application level), we disconnect a client that is still valid/active.  For some reason, this line (seems safe to close a socket here), causes the spam/spike on the server.  Adding our own application level ping/pong mechanism avoids the issue.

**Comment by alexhultman** [comment]
How long does it go 100% CPU? It should close down after 15 seconds.

**Comment by alexhultman** [comment]
The 100% CPU bug should be fixed in next release. Will add the 'pong' event shortly.

**Comment by alexhultman** [comment]
Could you check and see if 0.6.0 solves the CPU issue?

**Comment by alexhultman** [comment]
This should be fixed now. Will release this as 0.6.2 today.
