### ISSUE TITLE
use multi workor in nodejs

### ISSUE THREAD

**Issue by notedit** [alexhultman/uWebSockets#160]
there is a c++ version  multi workor in one instance.

how can i archive this  in nodejs?

**Comment by alexhultman** [comment]
You want to see an example like the examples/multithreaded_echo.cpp but for Node.js? It [uws] should work just like any other Node.js module as far as I know. You can either expose a port range, one port per process, or somehow distribute file descriptors via IPC in some way (I never tried this in Node.js).

**Comment by notedit** [comment]
i like the idea  multi worker node  base on libuv  from this repo  https://github.com/ibc/mediasoup

that is awsome  if uWebSockets will have this.

**Comment by alexhultman** [comment]
I don't follow. You use uws just like you use ws.
