### ISSUE TITLE
EBADPLATFORM while installing on Windows

### ISSUE THREAD

**Issue by darahand** [alexhultman/uWebSockets#162]
While README.md states "Linux, OS X & Windows support" I cannot install the package on Windows platform:
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code EBADPLATFORM

npm ERR! notsup Not compatible with your operating system or architecture: uws@0.6.1
npm ERR! notsup Valid OS:    darwin,linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

Seems like the following commit broke installation on windows: https://github.com/alexhultman/uWebSockets/commit/c9577d076067a562f96477d2b0ac7ef5b5737f6c
Is the package not supported on windows anymore?

Thanks,
Andrei.

**Comment by alexhultman** [comment]
The Node.js addon is not supported on Windows while the native C++ library is. It is a little bit misleading, maybe a lot misleading but the reason is Node.js does not really work as it should on Windows, the native Node.js SDK for Windows is broken so we cannot support Windows until Node.js devs fix this up.

**Comment by darahand** [comment]
Thank you for quick response, also found on the main page below that "Node.js is broken on Windows and needs to be fixed for us to support the platform". So as this is a known issue, will close mine. Sorry, my bad.

**Comment by alexhultman** [comment]
No problem, it can clearly be marked a lot more obvious.
