### ISSUE TITLE
Simpler UTF-8 check

### ISSUE THREAD

**Issue by marton78** [alexhultman/uWebSockets#17]
Hi,

you could try this snippet here:

http://bjoern.hoehrmann.de/utf-8/decoder/dfa/

M.

**Comment by alexhultman** [comment]
It will need to pass every Autobahn test (most UTF-8 validators I found did not). But I will try this one, thanks.

**Comment by alexhultman** [comment]
It did pass Autobahn and it could be simplified to only a few lines of code when only doing the validation. Thanks for the link.
