### ISSUE TITLE
PHP binding? CLI support as service?

### ISSUE THREAD

**Issue by BunnyHolder** [alexhultman/uWebSockets#19]
What about PHP binding?
Maybe simple cli support would be nice, like you can bind php script as message handler:
`wsService bind --in-message "hello" --out "php-cli script.php %message% %sid%"`

Edit: i'm thinking not only about lib, but maybe as normal linux service that can make communication over WS easear. Having simple bindable handlers would be extremely nice and universal. You could make any linux command line program to communicate over ws.

**Comment by alexhultman** [comment]
I don't have any plans for PHP support but if you want to add things like these I would accept them. The Node.js planned support is because of hype, basically. It gives a lot of free hype to support Node.js.
