### ISSUE TITLE
Transition to NAN

### ISSUE THREAD

**Issue by ronkorving** [alexhultman/uWebSockets#35]
[NAN](https://github.com/nodejs/nan) is what the world uses to keep libraries with compiled binaries in them compatible across a big range of Node versions. It would be wise to transition to it.

**Comment by alexhultman** [comment]
Yes I've heard of NAN but I rather use vanilla Google V8. The V8 interface is pretty stable and only breaks once in a while. I'm not going to keep compiling for more than 2-3 major versions of Node anyways. When it breaks, well then you have to upgrade your Node version or use an old version of the module.

**Comment by alexhultman** [comment]
Plus, I'm pretty sure I can update this sub 100 lines of addon in less time than those Node people can update their NAN.

**Comment by ronkorving** [comment]
Time will tell, I guess :)
