### ISSUE TITLE
Optimize JS wrapper

### ISSUE THREAD

**Issue by alexhultman** [alexhultman/uWebSockets#36]
@ronkorving Like I said, minimizing the JS overhead of each ws socket is something I see as very important and that would be awesome if you wanted to look at. It requires about 800 mb of memory for 1 million connections for me currently. The native server consumes 250 mb of memory, so any optimization to JS-land is appreciated.

**Comment by mattkrick** [comment]
Would be interesting to see a benchmark comparing the stock eventemitter vs https://github.com/primus/eventemitter3. Should give a little boost. 
Also, if your build target is node 4+, you'll get (albeit minimal) gains from using let & const since V8 can now optimize functions containing those keywords without bailing.

**Comment by alexhultman** [comment]
All kinds of optimizations are appreciated but I think the most primary should be about fixing the massive difference in memory usage, native vs. addon per connection.

**Comment by alexhultman** [comment]
I tried the eventemitter3 and it scales a little worse in memory: 1 million connections requires 680 mb with the built-in emitter and 730 mb with eventemitter3.

**Comment by ronkorving** [comment]
It does seem that at this point, EventEmitter probably is the biggest consumer of memory. The Socket class is already so incredibly thin now, that I don't see any remaining opportunities for reducing memory consumption. The event emitter on the other hand...

If you want to try one more emitter library, I wrote this one a while ago, optimized for performance (hopefully also for memory): https://github.com/Wizcorp/events

**Comment by alexhultman** [comment]
The thing (one thing) I don't like about the Node.js universe is that everything is bound by strings. In my opinion you should never ever use strings for other things than to hold text. Like when I emit an event by a string that string needs to be linearly searched and matched against a list of callbacks. That is very much insane and this is why we have enums in C++. The best event-emitter would "compile" the events into enums like this:

emitter.on('string', function) <- this is the public interface, nothing can be fixed here

but

integer eventId = emitter.resolveEventId('string') <- we get an *integer* to represent the event

then

when calling it in high perf, we simply pass the *integer* id:

emitter.emit(eventId);

**Comment by alexhultman** [comment]
events.js was about the same or maybe a little heavier than eventemitter3, 730-60 mb

**Comment by ronkorving** [comment]
I'm all for superior solutions :) And I understand the frustration. I guess that's one reason why ES6 introduces Symbol objects. But we have to live with this one I fear...

Thanks for the test on https://github.com/Wizcorp/events

**Comment by alexhultman** [comment]
Yeah I guess JavaScript is slowly becoming a normal language. When they add types, classes and symbols I can accept it as a real language but currently it is mindblowingly heavyweight.

**Comment by alexhultman** [comment]
Omfg, I tried this: https://github.com/HenrikJoreteg/wildemitter

"A super lightweight EventEmitter similar to what comes in Node.js, but with a support for wildcard events '*'"

It consumes 930 mb of ram. That is almost 2x more heavyweight than the stock emitter. *facepalm*

**Comment by alexhultman** [comment]
When I run the "native" JS-wrapper (the one that is not ws) it consumed 297 mb of ram. Essentially, the ws interface is broken by design.

**Comment by alexhultman** [comment]
So there are 2 flaws in the ws interface that could be the reason for this huge difference:

* in ws you register a closure to every connection (is the closure / function heavyweight?)
* they use EventEmitter (is eventemitter doomed to be heavyweight?)

**Comment by alexhultman** [comment]
What if you "hash" the 4 first byte of the event's string into a 4 byte integer and store it in a shared vector of pairs of 4 byte integers and a callback reference? That could be very efficient and lightweight and should cover all event emitted by the ws interface.

**Comment by ronkorving** [comment]
To be honest, the best thing you can do right now is profile this. Where exactly the bulk of the weight sits is hard to say right now. How do you benchmark btw? I would love to see that code.

**Comment by alexhultman** [comment]
The benchmarks are in the benchmarks folder (lol). Well I have stripped away a lot of stuff and the very fact that a socket is its own (JS) object makes a huge difference. If I remove EventEmitter completely from the Socket object, do not register any callbacks or anything then it consumes 420 mb of ram. So just the fact that we use JavaScript objects to represent sockets makes the server consume 2x more memory. *throws my screen out the window*

**Comment by ronkorving** [comment]
The JS in the benchmarks folder only benchmarks `ws`, right? Not this library.

**Comment by alexhultman** [comment]
All bechmarks are C++, the js code is just an echo server being used. I run bench1 to connect 1 million connections but this is probably only running on Linux and you need to set up like 30 localhost addresses to reach that many connections.

**Comment by ronkorving** [comment]
Right, so how do you benchmark Node land's memory use?

**Comment by alexhultman** [comment]
I benchmark the native server, benchmark the wrapped server and do subtraction.

**Comment by alexhultman** [comment]
One obvious optimization would be to implement the EventEmitter / Socket as one integrated thing.

```javascript
    on(event, f) {
        if (event == 'message') {
            this.messageCallback = f;
        } else if event == 'close' {
            this.disconnectionCallback = f;
	} // etc, etc
    }
```

This makes it drop from 680 mb down to 580 mb - and I get to call this.messageCallback directly without passing a string. If some crazy person has multiple listeners they simply need to register a function calling those multiple recipients.

**Comment by alexhultman** [comment]
f7b008da7c18329c6f3332c7b6c564c6ea384f01

This commit goes on the path on implementing our own simplified EventEmitter. This removes 100 mb of memory usage and makes calls higher-perf since we do not call functions using strings. I don't think this will break anything, people shouldn't rely that hard on EventEmitter I guess.

**Comment by alexhultman** [comment]
I'm pretty happy with this. 580 mb of ram for 1 million WebSocket connections in Node.js - that's pretty neat.

**Comment by ronkorving** [comment]
Assumptions do make an ass out of u and me. But I'm willing to give this a shot :)

**Comment by alexhultman** [comment]
Basically it is an EventEmitter with maxListeners hardcoded to 1.

**Comment by alexhultman** [comment]
088fb41c4c4893b9f617dc10de635dc36dfa30a0

550 mb with this thing.

**Comment by lpinca** [comment]
Honestly the current EventEmitter implementation is pretty useless.
If you want to go with this path then it's probably better to define two properties on the socket instance, initialize them as noop functions, and allow the user to overwrite them:

```js
/* ... */
constructor(nativeSocket, server) {
  this.onmessage = this.onclose = noop;
  this.nativeSocket = nativeSocket;
  this.server = server;
}
/* ... */

socket.onmessage = function whatever() {};
```

Ofc this is different from the `ws` interface but current code also is...
Also I wouldn't worry about 100 mb when dealing with 1 million connection, yeah the difference with C++ is huge but that's the price to pay I guess.

**Comment by alexhultman** [comment]
The purpose is not to create a full-fledged EventEmitter, the purpose is to get 99% of already written ws-code to run unmodified. If I only accept 1 listener or if I accept 10 is not going to matter in most cases. The question is - have you ever in your life registered more than one listener to a ws socket? And if so - why? Ofc, currently it can be a little sneaky as there is no error message when registering more than one listener - that could be fixed.

**Comment by lpinca** [comment]
Hard question I'm not sure, maybe I did maybe I didn't can't really remember but it doesn't matter.
It's ok to have a single listener for those events as it's just like it is in the browser, but as I said in this case I wouldn't use the EE interface.

**Comment by alexhultman** [comment]
If you don't use the EE interface you will get 0% compatibility. If having this simplified EE interface we get 99% compatibility and we can display an error in those cases where people add more than one listener. And since you cannot even remember if you have ever done this, I would say that would be an edge case where the user would need to adopt. This is never going to be a pure 100% match with ws, there are always going to be small quirks and differences.

**Comment by alexhultman** [comment]
Besides, I did this exact thing in node-lws and nobody has yet to report an issue. And I didn't even display an error in node-lws.

**Comment by alexhultman** [comment]
6046557fe82254d35d831cbc714c016c8c84e3cd

**Comment by lpinca** [comment]
Use a real error not a string, like:
```js
throw new Error(message);
```

**Comment by alexhultman** [comment]
I'm working on writing the ws wrapper in C++. When this is done we can compare the memory usage and see if there is a significant improvement in memory usage. If so, then the JS code will have to go. Otherwise, I guess this is as far as it goes.

**Comment by ronkorving** [comment]
My uneducated guess is we won't win much (if anything) with a full C++ implementation, but it may make things simpler to maintain in any case. Give it a shot. Looking forward to the results.

**Comment by alexhultman** [comment]
The server could still be JS but the socket object could be made an ObjectTemplate from within C++ and then constructed from JS. But I don't know if this will change things, maybe a little as I can store things a little better. One would think that a class declaration in JS-land would be the same as an ObjectTemplate in V8 though.

**Comment by ronkorving** [comment]
I think JS code gets optimized where C++ code just runs as-is, with more expensive type checking etc happening. I think the JIT will end up doing a better job than the V8 APIs can. Just my expectation though. There's not a lot of code at all in JS, so we may not even see a difference.

**Comment by alexhultman** [comment]
That would be incorrect. C++ is about a million times more optimizable than JS, and from V8 (which of course is the lowest level you can get in terms of JS) you can set hidden pointers to JS objects which are about a million times faster and more lightweight than setting/getting variables from "JS objects" (which are basically exactly like hashmaps in other languages). But I do not know if this will improve it significantly in this case.

**Comment by ronkorving** [comment]
I think you're missing the point. Of course C++ as a language is more optimizable. But you're still exposing an interface to JS. So all the non-strict typing is still relevant, and simply receiving an argument into a method (runtime type checks) is not as plain and simple as it is in C++ (compile time type checks). The JIT does a pretty good job of spitting out machine code based on heuristics that you simply wouldn't be writing in C++ land. Anyway, all this discussion is pretty irrelevant. Just give it a shot and see what happens.

**Comment by alexhultman** [comment]
I cannot make it any more lightweight since we still need to expose a JS object. The problem is that JS objects are like elephants, and we need a lot of elephants.
