### ISSUE TITLE
Crash on windows

### ISSUE THREAD

**Issue by peters** [alexhultman/uWebSockets#40]
Version: Latest master.
Libuv: 1.9.0
IDE: Visual Studio 2015 Update 2
Platform: Windows 10 x64

In order to get uWebSockets to build I had to make the following changes:

```cpp
#if _MSC_VER >= 1900
#include <io.h>
#if !defined(dup)
#define dup _dup
#endif
#if !defined(read)
#define read _read
#endif
#endif
```

Example code:

```cpp
int connections = 0;

uWS::Server server(44545);
server.onConnection([&connections](uWS::Socket socket) {
   cout << "[Connection] clients: " << ++connections << endl;
});

server.onMessage([&connections](uWS::Socket socket, const char *message, size_t length,
uWS::OpCode opCode) {
   cout << "[Message]: " << message << std::endl;
});

server.onDisconnection([&connections](uWS::Socket socket) {
    cout << "[Disconnection] clients: " << --connections << endl;
});

server.run();
```

Then I simply connect using a compliant .NET websocket client and send a message. Then, **BOOM** crash:

![image](https://cloud.githubusercontent.com/assets/869/14407895/28e93678-fedb-11e5-8cb2-35333f8de8ee.png)

![image](https://cloud.githubusercontent.com/assets/869/14407897/42cc98f0-fedb-11e5-80d8-f7d6212376d0.png)

**Comment by alexhultman** [comment]
I've tested it in Windows 10 and it worked fine but I did not test after adding dup. Will take a look at this, thanks.

**Comment by alexhultman** [comment]
You shouldn't have to define read. It should use recv.

**Comment by alexhultman** [comment]
I have missed to change onReadable to use recv. You see I use recv in onAcceptable. Should be the same in onReadable.
