### ISSUE TITLE
Reduce V8/JS barrier switches

### ISSUE THREAD

**Issue by ronkorving** [alexhultman/uWebSockets#41]
The onMessage returns a nativeSocket reference which we then have to turn into a Socket through getData() which means that when onMessage is triggered, we immediately jump back into C++ land. There's a cost associated with that.

Similarly when onDisconnection is called, we call into C++ land twice. Once to get the Socket and once to forget about the Socket. That too has a cost.

The only case where I see a real need for a nativeSocket value is in connectionCallback, where we instantiate the Socket. I understand that works better in JS than in C++, so I wouldn't change that. All other cases though...

**Comment by alexhultman** [comment]
I could make all callbacks pass along any set data.

**Comment by ronkorving** [comment]
I think that would do the trick just fine :+1:
