### ISSUE TITLE
Running outside of node.js

### ISSUE THREAD

**Issue by peters** [alexhultman/uWebSockets#43]
On line [247](https://github.com/alexhultman/uWebSockets/blob/master/src/uWS.cpp#L247) the uv event loop is instantiated with `UV_RUN_DEFAULT`. This blocks the main thread. Would it be horrible to add a `uv_timer_t` that checks if a `shutdown` is scheduled? 

I'm not that familiar with `libuv` but it would be nice to avoid forking a new thread just to contain the event loop in order to shutdown `uWS` when the `dtor` of our wrapper class is called.

In `libav` (ffmpeg) you have the ability to specify an interrupt callback and if you return `0` it will break out of it's main loop.

Please excuse my ignorance :dancers: 

/cc @alexhultman

**Comment by alexhultman** [comment]
Server::run runs the event-loop, yes? That will block the thread until Server::close has been called. I don't understand the question / problem? You want to register a signal handler?

**Comment by peters** [comment]
A signal handler would be nice. The application I'm integrating your library into is highly multi-threaded one (distributed across many machines). What I'm essentially researching if your implementation would improve our overall throughput :)

**Comment by peters** [comment]
There also seem to be some synchronization issues when tearing down connections. In a simple test scenario, I'm fork around 10,000 connections constantly connecting/disconnecting and when calling `close(forceClose=true)` there seem to be a heap corruption issue. I'm investigating that right now and I'll post an analysis on the matter.

**Comment by alexhultman** [comment]
The only synchronization supported is in the thread safe functions, aka upgrade and close. All other modifications of the servers from other threads are thread unsafe. I've had millions and millions of connections using the threaded echo server though.

**Comment by peters** [comment]
I think it was related to me incorrectly using `dup`. After landing https://github.com/alexhultman/uWebSockets/pull/47/files the tests pass.

**Comment by peters** [comment]
Maybe you could create a new issue for the signal handler itself and I can send a PR for it? That is if you don't want to do it yourself.

**Comment by alexhultman** [comment]
When are you using dup? Dup is only indented for use with other HTTP servers.

**Comment by peters** [comment]
I think that I removed this https://github.com/alexhultman/uWebSockets/blob/master/src/uWS.cpp#L374 if statement accidentally when trying to figure out what was going on. Sorry about the mess, been pushing a lot of hours lately, and that sometimes makes you sloppy :/
