### ISSUE TITLE
Seamless SSL transfer

### ISSUE THREAD

**Issue by alexhultman** [alexhultman/uWebSockets#52]
This feature is needed to reach more than a few Node.js developers. The transfer from https.Server to µWS should be as seamless as in other implementations.

While adding SSL support is pretty straight-forward, making sure to properly transfer an existing SSL connection from Node.js to us is not as trouble-free. It seems to be possible though, being passed a tls.TLSSocket should make it possible to get the underlying TLSWrap which exposes the ssl() function returning the SSL pointer which is reference counted.

**Comment by alexhultman** [comment]
tls.TLSSocket.ssl._external should give the SSL pointer, but this feature seems broken in Node.js for the time being.

https://github.com/nodejs/node/issues/6338

**Comment by alexhultman** [comment]
This issue was a duplicate and was fixed already. Should land in the next Node updates (4.x, 5.x). Should probably be part of 6.x also.

**Comment by alexhultman** [comment]
I seem to have a working seamless SSL transfer now. It works in Node 5.x and seems Valgrind clean. I can send messages over SSL connections established by the Node.js HTTPS server.

```javascript
https.createServer(options, (req, res) => {

  /* SSL, FD, secKey */
  addon.transfer(req.socket.ssl._external, req.socket._handle.fd);
  res.socket.destroy();
  addon.write();
  setTimeout(() => {
    console.log('Ending SSL connection now');
    addon.end();
  }, 1000);

}).listen(8000);
```

```c++
/* part of the WebSocket */
SSL *ssl;

void transfer(const FunctionCallbackInfo<Value> &args)
{
    /* get FD, SSL * */
    int fd = args[1]->IntegerValue();
    ssl = (SSL *) args[0].As<External>()->Value();

    /* Node.js DestroySSL calls SSL_free */
    ssl->references++;
    /* Node.js want to delete its own BIO's */
    SSL_get_rbio(ssl)->references++;
    SSL_get_wbio(ssl)->references++;

    /* dup the fd, set new BIO */
    SSL_set_fd(ssl, dup(fd));
}

void write(const FunctionCallbackInfo<Value> &args) {
    SSL_write(ssl, "The quick brown fox jumps over the lazy dog", 43);
}

void end(const FunctionCallbackInfo<Value> &args) {
    SSL_shutdown(ssl);
}
```

**Comment by LordMajestros** [comment]
Good news. I have a working port of engine.io to uws. I'll put it up. It still has a few issues passing the all socket.io tests but in time.

**Comment by alexhultman** [comment]
Nice, keep running these tests and report issues :)
