### ISSUE TITLE
Socket.IO comparison

### ISSUE THREAD

**Issue by joezimjs** [alexhultman/uWebSockets#53]
From what I've seen, Socket.io is the most popular Websocket implementation for NodeJS, but I don't see them in your benchmark chart. I'm thinking it's because they not as focused on performance, and more focused on making things simpler with more features, so the comparison may not be fair, but I still think it's a good thing to compare, because if this is many times faster, then it may be worth looking at this as an alternative.

**Comment by alexhultman** [comment]
Socket.io is from my understanding based on engine.io which is using ws under the hood. But you don't realy need to do any comparison as I do not rely on uv_tcp_t (the net.Socket) but rather uv_poll_t. The overhead of a single uv_tcp_t is enough to blow the memory scaling of only using uv_poll_t.

**Comment by joezimjs** [comment]
good enough for me
