### ISSUE TITLE
What's the reason why you're faster than ws?

### ISSUE THREAD

**Issue by binarykitchen** [alexhultman/uWebSockets#56]
https://github.com/websockets/ws

They claim to be the fastest RFC-6455 WebSocket implementation for Node.js ...

... so would be good to have neutral explanations and facts.

**Comment by alexhultman** [comment]
I don't want to start a flame, but I did raise this exact question a couple of months ago and I was blocked, censored and name-called. So I have stopped caring what others think. If you are questioning my benchmarks I can assure you that there exists no universe in which ws is faster than µWS.

**Comment by binarykitchen** [comment]
@alexhultman Understand. Do not want to ignite a flame war. I am just neutral here and questioning the facts. Because I really need super-fast web sockets for my www.videomail.io app where in average over 400 Deaf people communicate every day in Sign Language.

So yes, you say you can assure that µWS is faster than ws. Do you have more facts and details on those measurements?

**Comment by alexhultman** [comment]
I have published all my benchmarks under benchmarks folder. Feel free to validate them.

**Comment by binarykitchen** [comment]
@alexhultman Will do. Can you outline for now here, why yours is faster than theirs? What are you doing differently than ws? What's the trick?

**Comment by alexhultman** [comment]
I did a reddit post in the C++ subredit you can read all the questions there.

**Comment by binarykitchen** [comment]
Link?

**Comment by alexhultman** [comment]
You can google it, you will find it.

**Comment by alexhultman** [comment]
In any case, if you are considering ws or µWS then it doesn't really matter what you chose. We both implement the same interface and you can easily swap whenever you want. You should never listen to what others tell you, always do your own benchmarkings. In the end, it is your product that needs to be benchmarked, not one particular library.

**Comment by alexhultman** [comment]
I just ran a benchmark for you:

```
[alexhultman@localhost benchmarks]$ ./bench2 10000 3000
Echo performance: 235.058 echoes/ms
Echo performance: 225.932 echoes/ms
Echo performance: 211.675 echoes/ms
Echo performance: 213.163 echoes/ms
Echo performance: 213.626 echoes/ms
Echo performance: 213.816 echoes/ms
Echo performance: 212.596 echoes/ms
Echo performance: 211.237 echoes/ms
Echo performance: 210.845 echoes/ms
Echo performance: 210.351 echoes/ms
Echo performance: 208.914 echoes/ms
Echo performance: 208.239 echoes/ms
Echo performance: 208.052 echoes/ms
Echo performance: 207.963 echoes/ms
Echo performance: 207.285 echoes/ms
Echo performance: 206.92 echoes/ms
Echo performance: 206.856 echoes/ms
Echo performance: 206.891 echoes/ms
Echo performance: 207.027 echoes/ms
Echo performance: 207.123 echoes/ms
Echo performance: 206.666 echoes/ms
Echo performance: 206.542 echoes/ms
Echo performance: 206.737 echoes/ms
Echo performance: 206.933 echoes/ms
Echo performance: 207.087 echoes/ms
Echo performance: 207.42 echoes/ms
Echo performance: 207.529 echoes/ms
Echo performance: 207.522 echoes/ms
Echo performance: 207.518 echoes/ms
Echo performance: 207.549 echoes/ms
Echo performance: 207.592 echoes/ms
Echo performance: 207.6 echoes/ms
Echo performance: 207.632 echoes/ms
Echo performance: 207.804 echoes/ms
Echo performance: 207.94 echoes/ms
Echo performance: 208.163 echoes/ms
Echo performance: 208.186 echoes/ms
Echo performance: 208.29 echoes/ms
Echo performance: 208.498 echoes/ms
Echo performance: 208.568 echoes/ms
Echo performance: 208.767 echoes/ms
Echo performance: 208.849 echoes/ms
Echo performance: 208.87 echoes/ms
Echo performance: 209.027 echoes/ms
Echo performance: 209.071 echoes/ms
Echo performance: 208.913 echoes/ms
Echo performance: 208.874 echoes/ms
Echo performance: 208.858 echoes/ms
Echo performance: 208.826 echoes/ms
Echo performance: 208.752 echoes/ms
Echo performance: 208.808 echoes/ms
Echo performance: 208.794 echoes/ms
Echo performance: 208.826 echoes/ms
Echo performance: 208.809 echoes/ms
Echo performance: 208.727 echoes/ms
Echo performance: 208.602 echoes/ms
Echo performance: 208.598 echoes/ms
Echo performance: 208.524 echoes/ms
Echo performance: 208.535 echoes/ms
Echo performance: 208.461 echoes/ms
Echo performance: 208.378 echoes/ms
Echo performance: 208.369 echoes/ms
Echo performance: 208.349 echoes/ms
Echo performance: 208.234 echoes/ms
Echo performance: 208.17 echoes/ms
Echo performance: 208.132 echoes/ms
Echo performance: 208.028 echoes/ms
Echo performance: 207.914 echoes/ms
Echo performance: 207.92 echoes/ms
Echo performance: 207.873 echoes/ms
Echo performance: 207.905 echoes/ms
Echo performance: 207.935 echoes/ms
^C
[alexhultman@localhost benchmarks]$ ./bench2 10000 3000
Echo performance: 26.8528 echoes/ms
Echo performance: 27.9283 echoes/ms
^C
[alexhultman@localhost benchmarks]$ ./bench2 10000 3000
Echo performance: 29.6068 echoes/ms
Echo performance: 30.9768 echoes/ms
Echo performance: 31.369 echoes/ms
Echo performance: 31.6387 echoes/ms
Echo performance: 31.7748 echoes/ms
```

This server is identical in code, but run with 1. µWS, 2. ws with binary addons installed, 3. ws without binary addons installed.

Note though that the benchmark is not even enough to stress µWS fully, while ws is at 100% CPU usage. You can see that in this benchmark where I send small messages the overhead of ws's binary addons actually hurt performance, so I wanted to show you how it performed without them. As you can see, the difference is obvious.

**Comment by FlorianBELLAZOUZ** [comment]
[The reddit post ](https://www.reddit.com/r/cpp/comments/4ccpsa/%C2%B5websockets_highly_scalable_c11_websocket_server/)  @binarykitchen
