### ISSUE TITLE
Add code and data to websocket.close

### ISSUE THREAD

**Issue by jtut1731** [alexhultman/uWebSockets#57]
Looking at trying to convert from ws to this library.  Looks promising.  I currently make use of codes sent during websocket.close.  uWebSockets' close does not support websocket.close([code], [data]) like the ws library has that I need.  Any possibility of adding this support?

**Comment by alexhultman** [comment]
Hi, I'll take a look at this. Thanks for reporting any interface differences.

**Comment by alexhultman** [comment]
This is working and solved now in C++ but I need to fix up the wrapper also.
