### ISSUE TITLE
Few values like _socket.remoteAddress and _socket.remotePort are undefined

### ISSUE THREAD

**Issue by abhishekgahlot** [alexhultman/uWebSockets#59]
Hi,

I tried using this library in my current ws based app but these variables are undefined and these are helpful for logging too.
ws._socket.remoteAddress
ws._socket.remotePort
ws.upgradeReq.url

Thanks

**Comment by LordMajestros** [comment]
+1

**Comment by alexhultman** [comment]
These properties are most probably not part of the "public" interface. _socket seems to be a net.Socket which is not used in µWS. The same goes for upgradeReq. You only get upgradeReq when using the Node.js HTTP server but not when using the built-in HTTP server in µWS (simply because that server is not the Node.js HTTP server and will not act as it).

If you need the upgradeReq you have to use the Node.js HTTP server (by using handleUpgrade, or specifying server and path in the construction options). See nodejs/paths.js for an example.

**Comment by alexhultman** [comment]
If you need to get the remoteAddress aka the client IP that could be added as a functionality. But I cannot add it as a variable in an object _socket since that would require a ton of memory (each JS object is massive). It could be made a function of the socket like socket.getRemoteAddress().

**Comment by JrSchild** [comment]
This may sound like a really random idea. But hypothetically speaking you could make one 'variable' _socket object that implements an ES6 getter method to retrieve the value of `socket.getRemoteAddress()`. Each connection always gets the same _socket object.

Something like this:
```
var _socket = {
  get remoteAddress() {
    return socket.getRemoteAddress();
  }
  get remotePort() {
    return socket.getRemotePort();
  }
}
```
Then all you have to do is use this same object for each 'separate' connection. This way you can shim the current behavior to some extend and you save loads of memory.

Just curious what you think

**Comment by alexhultman** [comment]
This shared object, how would it know what socket to get from?

**Comment by alexhultman** [comment]
Can I have a get function for _socket, returning a reference to the shared _socket?

**Comment by alexhultman** [comment]
class Socket {

get _socket() {
remoteAddress = lalala;
remotePort = lalala;
}

}

**Comment by alexhultman** [comment]
I removed some of my comments, but in short: using those get functions it should be possible to write something like:

class Socket {
get _socket() {
return {
this.remoteAddress = ...;
this.remotePort = ...;
}
}
}

Aka, construct a new object when it is read from, containing the variables with data set.

**Comment by alexhultman** [comment]
@JrSchild I did this:

```javascript
    /**
     * Phony _socket object constructed on read.
     *
     * @public
     */
    get _socket() {
        return {
            remoteAddress: '...',
            remotePort: 0
        };
    }
```

Where '...' will be replaced with real information. Thanks for the hint!

**Comment by ronkorving** [comment]
Brilliant solution, and on the prototype, so this costs 0 extra memory.

**Comment by abhishekgahlot** [comment]
Thanks @alexhultman
