### ISSUE TITLE
Implement Socket.once

### ISSUE THREAD

**Issue by asafyish** [alexhultman/uWebSockets#63]
Hi,

In ws I can use ws.once, but in uws, once doesn't exist.
ws.once is useful for cases like 'close' event, which I want to do a one time cleanup, and then let socket be gced. with ws.on, I cannot be sure it will be gced.

**Comment by ronkorving** [comment]
A close event only ever fires once, so `on` should be completely safe. But `once` could be a cheap alias to `on` here.

**Comment by Michael77** [comment]
Hey @alexhultman here is a PR for this: https://github.com/alexhultman/uWebSockets/pull/67

I wasn't able to test it properly because I had trouble on my mac, so let me know if this works.

**Comment by alexhultman** [comment]
@Michael77 Thanks, I didn't test it but it looks okay.

**Comment by dvergeylen** [comment]
Hi @alexhultman, @Michael77,

I am experiencing some trouble that took me quiet some time to figure out. It seems that the implementation of [#67](https://github.com/uWebSockets/uWebSockets/pull/67) doesn't call the given function as a tail call.

This means that `this.internalOnMessage` is not equal to `noop` when you are in the callback, preventing you to add a listener again. Wouldn't it be a reasonable assertion to expect being "free of listener" once in the callback (which is trigged *after* the event occurred)?

Just my two cents but swapping the statements seems sufficient to ensure `f()` as a Tail call.

```diff
once(eventName, f) {
        if (eventName === 'message') {
            if (this.internalOnMessage !== noop) {
                throw Error(EE_ERROR);
             this.internalOnMessage = (message) => {
-                f(message);
                 this.internalOnMessage = noop;
+                f(message);
             };
         } else if (eventName === 'close') {
             if (this.internalOnClose !== noop) {
                 throw Error(EE_ERROR);
             }
             this.internalOnClose = (code, message) => {
-                f(code, message);
                 this.internalOnClose = noop;
+                f(code, message);
             };
         } else if (eventName === 'ping') {
             if (this.onping !== noop) {
                 throw Error(EE_ERROR);
             }
             this.onping = () => {
-                f();
                 this.onping = noop;
+                f();
             };
         } else if (eventName === 'pong') {
             if (this.onpong !== noop) {
                 throw Error(EE_ERROR);
             }
             this.onpong = () => {
-                f();
                 this.onpong = noop;
+                f();
             };
         }
         return this;
}
```

I can submit a pull request if you'd agree on this.

**Comment by alexhultman** [comment]
👍

**Comment by dvergeylen** [comment]
[#421](https://github.com/uWebSockets/uWebSockets/pull/421)
