### ISSUE TITLE
Support verifyClient when 'server' is not provided

### ISSUE THREAD

**Issue by asafyish** [alexhultman/uWebSockets#64]
Hi,

I was using ws, and was trying this library, my verifyClient was not called, after some digging, it looks like I need to provide a server parameter with a native server for it to work, which is not the case in ws.

**Comment by alexhultman** [comment]
Currently there are some inconsistencies depending on what server options you pass. If you pass the port option you will get the (µWS) built-in HTTP server. This server does not (yet) have any 'upgrade' event where connections can be filtered. It doesn't add the upgradeReq either.

I've thought about this and I will probably make everything go though the Node.js HTTP server. This will reduce connection performance a lot though.

**Comment by asafyish** [comment]
The most compelling feature of uws is performance. So I am fine with
inconsistency, as long as it's documented somewhere.

Great lib BTW  😀

**Comment by ronkorving** [comment]
The ability to share the socket with the HTTP server is incredibly relevant though. This is an important feature for the web (to avoid CORS situations).

**Comment by alexhultman** [comment]
This issue will be solved in #97
