### ISSUE TITLE
Using http.createServer

### ISSUE THREAD

**Issue by 131** [alexhultman/uWebSockets#66]
Is it possible for uws to plug itself to an existing instance of (a dummy) nodejs http server (as i do not want to create/listen a new port for my application) ?
I look the source code a little, without finding proper documentation or sample around this point..
Thanks for your help

**Comment by alexhultman** [comment]
https://github.com/alexhultman/uWebSockets/blob/master/nodejs/paths.js

You specify `server` as option. I'm not sure if it works without any `path` option. It should.

**Comment by 131** [comment]
This is exactly what i was looking for, thank you very much !
