### ISSUE TITLE
Write a Node.js wrapper

### ISSUE THREAD

**Issue by alexhultman** [alexhultman/uWebSockets#7]
From my last experiment, I found that the `ws` interface is very popular and widely used. It would make more sense to directly target this interface to reach the widest possible audience.

`require('ws')` should pretty much be replaced with `require('uws')`, with some minor differences of course.

**Comment by alexhultman** [comment]
#29

**Comment by ronkorving** [comment]
FWIW, I wouldn't mind at all to help out on this project, especially the JS side, to keep it user friendly without sacrificing in performance. Let me know if you're interested.

**Comment by alexhultman** [comment]
Sure, I will be committing an initial wrapper in a short while. It is kind of the same deal as with node-lws but a lot more minimal.

**Comment by alexhultman** [comment]
This time the user facing code will be JS while the native wrapper will be as minimal as possible, essentially just wrapping functions as is. Then the JS wrapper will wrap this minimal interface into the ws interface and whatnot. That way we can expose real EventEmitters and such.

**Comment by ronkorving** [comment]
Great, looking forward to your first iteration on this.

**Comment by alexhultman** [comment]
@ronkorving Are you on Linux? I will commit most of the Node.js wrapper today.

**Comment by ronkorving** [comment]
I'm on OSX.

**Comment by ronkorving** [comment]
Looks good so far. I think some JS optimizations may be possible, and I can look into that. Impact will probably be minimal since we're dealing with an I/O bottleneck before a CPU bottleneck I'm guessing. I also expect a measurable positive impact on memory use can be achieved.

On another note, it would still be nice if the socket's send method could return an indicator if buffers are full or not. That way streams could be wrapped around it.

**Comment by alexhultman** [comment]
There are a few places where things can be simplified, and using prototype functions instead of setting them in each function is said to be faster. So yeah, that would be nice if you took a peek.

**Comment by alexhultman** [comment]
I've done a lot of testing and everything looks set for a release, but I have accumulating memory usage when connecting millions of connections. Maybe I'm not releasing the EventEmitters properly or something. I'll try to force the GC and see if that changes it.

**Comment by ronkorving** [comment]
Re. the memory use, I see you call `setData` to remember the Socket object, but I don't see you clean it up on disconnect. I may be overlooking something, but perhaps that's what's happening?

**Comment by alexhultman** [comment]
That would probably be it. I mark the reference as persistent when I setData.
