### ISSUE TITLE
Not all sent messages are received, OS X

### ISSUE THREAD

**Issue by lpinca** [alexhultman/uWebSockets#71]
**OS:** OS X 10.11.4
**Node:** 5.11.0
**uws:** 0.2.6
**ws:** 1.1.0

**Test case:**
```js
'use strict';

const crypto = require('crypto');
const uws = require('uws');
const ws = require('ws');

const messages = [];
let i = 10000;

while (i--) {
  const size = Math.floor(Math.random() * 1000) + 1;
  messages.push(crypto.randomBytes(size));
}

const server = new uws.uws.Server(8080);

server.onMessage((socket, message, binary) => server.send(socket, message, binary));

const socket = new ws('ws://localhost:8080');

socket.on('open', () => messages.forEach(message => socket.send(message)));
socket.on('message', () => {
  console.log(++i);

  if (i !== messages.length - 1) return;

  socket.close();
  server.close();
});
```

**Expected result:**
All messages are sent back to client.

**Actual result:**
Only some messages are sent back to the client.

**Comment by ronkorving** [comment]
You're completely flooding the send-buffer when the "open" event fires. It's no miracle that not all reach the other end imho.

**Comment by lpinca** [comment]
Works fine on Linux and when using ANY other ws server on OSX.

**Comment by ronkorving** [comment]
I can imagine, but raise the number further and you will reach a ceiling I imagine. This module's buffers are smaller than the ones Node applies to its own TCP streams iirc.

**Comment by lpinca** [comment]
> I can imagine, but raise the number further and you will reach a ceiling I imagine.

Yes I know, thanks.

This example was working fine also with the old `lws` module on all supported platforms, that's why I'm filing this issue.

**Comment by ronkorving** [comment]
I'll leave it to @alexhultman :)

I just hope that this is you just trying to find the limits of the project, rather than an actual use case though?

**Comment by lpinca** [comment]
@ronkorving yeah it's part of an old benchmark that was testing performance of various ws implementations (ws, faye-websocket, node-yawl, etc).

**Comment by alexhultman** [comment]
This should work, I'll try and reproduce this.

**Comment by alexhultman** [comment]
Those who tumb'd up the post, did you also reproduce this?

**Comment by alexhultman** [comment]
This freeze, is the CPU at 100% or 0%? Does it happen often? There are still things to fix in the Socket::write function which calls all the networking code. There are some cases I haven't properly checked fully.

**Comment by lpinca** [comment]
CPU is a 0%, it happens every time. ~600/10000 messages reach the client.

**Comment by alexhultman** [comment]
If you do a profiling https://nodejs.org/en/docs/guides/simple-profiling/

How does that look?

**Comment by lpinca** [comment]
I'll do that later and let you know.

**Comment by lpinca** [comment]
@alexhultman I can't see anything obvious. Here is the [file](https://github.com/alexhultman/uWebSockets/files/236033/processed.txt).

**Comment by alexhultman** [comment]
Could you add a 'close' listener for the ws socket? Send can fail and close the socket.

**Comment by lpinca** [comment]
```js
socket.on('close', () => console.log('closed'));
```

Not fired.

**Comment by alexhultman** [comment]
I just reproduced this. Man, you are doing some nice testing.

**Comment by alexhultman** [comment]
Well the issue is not in send. If you remove the send completely and count the number of times onMessage gets called you see it never gets the right amount of messages.

**Comment by lpinca** [comment]
Yeah I noticed that.

**Comment by alexhultman** [comment]
Have you tried with a different client?

**Comment by lpinca** [comment]
Yes, I tried with faye-websocket client, same stuff.

**Comment by alexhultman** [comment]
Could you add a timer that fires a function printing something like every second or so? To see that the event-loop is properly running after this happens. I have a little short on time now and I don't know how to write { } braces on OS X.

**Comment by lpinca** [comment]
@alexhultman I'll do that as soon as I can.

**Comment by alexhultman** [comment]
Also, see if the server can echo other messages after this. So keep it running but try and connect to it via websocket.org demo client or something and see if the server is still functioning.

**Comment by alexhultman** [comment]
Actually, you don't need to add a timer. The very check with websocket.org is enough. I tried it and it still works perfectly. I can connect and send messages and they will up the counter still. So the event-loop and everything is still working.

**Comment by alexhultman** [comment]
Well one very obvious check would be to see if the total size of what the server receives from the system is less than the total size of what you send. If this is, then the problem is not in the server.

**Comment by alexhultman** [comment]
Also, the total size of what is received from the system should pretty much match exactly with the total size of what is reported by onMessage (neglecting the size of the headers of all messages).

**Comment by lpinca** [comment]
Ok this is interesting. I've updated the example like this:
```js
'use strict';

const assert = require('assert');
const crypto = require('crypto');
const uws = require('uws');
const ws = require('ws');

const messages = [];
let i = 10000;

while (i--) {
  const size = Math.floor(Math.random() * 1000) + 1;
  messages.push(crypto.randomBytes(size));
}

const server = new uws.uws.Server(8080);

server.onMessage((socket, message, binary) => {
  console.log(++i);
  assert.deepStrictEqual(message, messages[i]);
  server.send(socket, message, binary);
});

const socket = new ws('ws://localhost:8080');

socket.on('open', () => messages.forEach(message => socket.send(message)));
socket.on('message', () => {
  if (i !== messages.length - 1) return;

  socket.close();
  server.close();
});
```

Note the assertion in the listener. The assertion fails, so I thought about out of order messages and added in the listener:

```js
const buf = messages.find(msg => msg.compare(message) === 0);
assert.ok(buf);
```

This also fails. It seems that at some point the listener is called with corrupted data, or the client sends corrupted data.

**Comment by LordMajestros** [comment]
I had a similar issue when running socket.io tests with my port of engine.io to uws. Corrupted data makes some tests fail. I think it has to do with utf8 encoding/decoding on the ws side. Here is a screen shot of the data logged to the console.
<img width="1440" alt="screen shot 2016-04-24 at 6 49 43 pm" src="https://cloud.githubusercontent.com/assets/10727946/14844297/64a6dfa0-0c4e-11e6-9dab-212220207810.png">

**Comment by alexhultman** [comment]
d65283184225445dc6fb60589e00a6f9fd8a45e6

This fixes it. The parser quit mid-parsing because it thought the socket was closed because I used "socket" (the global UNIX syscall) to denote socket. It's called p...

**Comment by LordMajestros** [comment]
I'll try this out later

**Comment by alexhultman** [comment]
Nice testing, this fixes one of the 8 paths in the parser. It was **completely** broken. :+1:

**Comment by lpinca** [comment]
@alexhultman can you publish a new release?

**Comment by alexhultman** [comment]
Done, one thing to note on this benchmark though is that you are going to get a ton of better performance on Linux. This because you echo a bunch of small messages that are being sent as one big chunk. This is why I use TCP_CORK on Linux to cork the sending into large packets, this is not supported on OS X so you will send a lot of small packages and lose perf. At least that was the case on Linux before I added the corking.

**Comment by alexhultman** [comment]
assert.deepStrictEqual(message, messages[i]);

This fails because the parser went like this:

Receive data
Emit message
Emit message
Emit message
Emit message
Receive data
Emit message
Receive data
Emit message

So it began correct, but then it would only emit the first message of every receive that's why you got "out of order" messages.

**Comment by lpinca** [comment]
@alexhultman thanks, it makes sense.

**Comment by lpinca** [comment]
Hmm new inconsistency. Everything is fine with `ws` client but if I try with `faye-websocket` it fails.

**Test case:**

```js
'use strict';

const WebSocket = require('faye-websocket');
const assert = require('assert');
const crypto = require('crypto');
const uws = require('uws');

const buf = crypto.randomBytes(1000);

const server = new uws.uws.Server(8080);

server.onMessage((socket, message, binary) => {
  assert.deepStrictEqual(buf, message);
  server.send(socket, message, binary);
});

const socket = new WebSocket.Client('ws://localhost:8080');

socket.on('open', () => socket.send(buf));
socket.on('message', message => {
  assert.deepStrictEqual(buf, message);
  socket.close();
  server.close();
});
```

data received in the listener is not the expected one. I thought about a bug in `faye-websocket` client, but if I switch the server to `ws` or `faye-websocket` it works as intended. This is kinda weird 😕 .

**Comment by alexhultman** [comment]
We should probably open a separate issue for this. I reproduced it but it seems very strange.

**Comment by lpinca** [comment]
I'll file a new issue in a bit.

**Comment by alexhultman** [comment]
From my testing it seems that the buffer you pass to faye gets overwritten. The comparison is failing because the buf gets scrambled up. If you copy buf into buf2 and compare buf2 with message it matches. You can also see this by sending new Buffer('Obvious string') and you'll get "Obvious string" as message.

Seems like faye takes ownership of any Buffer passed to send (maybe they mask the message inplace?).

**Comment by lpinca** [comment]
I'm not sure, I should take a look, nice catch btw.

**Comment by alexhultman** [comment]
This code passes fully:

```javascript
'use strict';

const WebSocket = require('faye-websocket');
const assert = require('assert');
const crypto = require('crypto');
const uws = require('uws');

const buf = crypto.randomBytes(1000);
const copiedBuffer = Buffer.from(buf);

const server = new uws.uws.Server(8080);

server.onMessage((socket, message, binary) => {
  assert.deepStrictEqual(copiedBuffer, message);
  server.send(socket, message, binary);
});

const socket = new WebSocket.Client('ws://localhost:8080');

socket.on('open', () => socket.send(buf));
socket.on('message', message => {
  assert.deepStrictEqual(copiedBuffer, message.data);
  socket.close();
  server.close();
});
```

**Comment by lpinca** [comment]
> I thought about a bug in `faye-websocket` client, but if I switch the server to `ws` or `faye-websocket` it works as intended.

This is not true, I probably messed up something before.

@alexhultman is right, the buffer is mutated when the [mask is applied](https://github.com/faye/websocket-driver-node/blob/2be829546b462aa7d552214e17d6f3e42b6a4bd0/lib/websocket/driver/hybi.js#L269).

This is indeed an issue in `faye-websocket`.

**Comment by lpinca** [comment]
I'm now back at the original test case but using `faye-websocket` instead of `ws` as client:

```js
'use strict';

const WebSocket = require('faye-websocket');
const crypto = require('crypto');
const uws = require('uws');
const ws = require('ws');

const messages = [];
let i = 10000;

while (i--) {
  const size = Math.floor(Math.random() * 1000) + 1;
  messages.push(crypto.randomBytes(size));
}

const server = new uws.uws.Server(8080);

server.onMessage((socket, message, binary) => {
  console.log(++i);
  server.send(socket, message, binary);
});

// const server = new ws.Server({ port: 8080 });

// server.on('connection', socket => {
//   socket.on('message', message => {
//     console.log(++i);
//     socket.send(message);
//   });
// });

const socket = new WebSocket.Client('ws://localhost:8080');

// const socket = new ws('ws://localhost:8080');

socket.on('open', () => messages.forEach(message => socket.send(message)));
```

Only some messages are received on the server. It works if I use `ws` as server.

Let me know if it's better to open a new issue.

**Comment by lpinca** [comment]
The above example works on linux.

**Comment by lpinca** [comment]
It doesn't seem to make a difference but shouldn't `socket` [here](https://github.com/alexhultman/uWebSockets/blob/7343fd8e03ec9091969001eff721b4875f83fc2c/src/uWS.cpp#L855) be `p`?

**Comment by alexhultman** [comment]
Yes it is the same flaw. Wanna make a PR?
