### ISSUE TITLE
Amazon/RedHat issue - Error: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found

### ISSUE THREAD

**Issue by jondubois** [alexhultman/uWebSockets#75]
While testing on Amazon (based on Redhat), this error came up:

Error: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /home/ec2-user/sc-test/node_modules/uws/uws_linux_47.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:422:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ec2-user/sc-test/node_modules/uws/uws.js:5:13)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)

Looks like the c compiler of Amazon's Distro (and maybe Redhat too) is not supported?

**Comment by alexhultman** [comment]
Amazon uses ancient compiler versions. Either I have to bundle my version of libstdc++ or link statically.

**Comment by jondubois** [comment]
Yeah, I guess linking statically or bundling might be worthwhile... If it doesn't add too much filesize. Portability is pretty important when it comes to Node.js.

**Comment by alexhultman** [comment]
Another solution could possibly be to compile it using an older compiler, I think that will solve itself if I opt for using Travis because they are also using ancient versions (their Ubuntu version is from the stone age).

**Comment by alexhultman** [comment]
#54

**Comment by alexhultman** [comment]
I don't think it's a good idea bundling libstdc++. It's 1.6 MB large and should really not be bundled IMO. I still think the best choice is to just use an older C++ compiler. If you look at Node.js itself, it also depends on libstdc++ but they don't ship it - they simply compiled Node.js using an older compiler.

But I still need to solve this, I use Fedora which comes with very up to date compilers and I'm not going to swap to some crappy ancient Ubuntu shit, so I need to set up Travis or any other service to get this working.

**Comment by alexhultman** [comment]
@jondubois What version of RHEL are you running? Version 7 could be a good target, right?

**Comment by jondubois** [comment]
@alexhultman I'm not sure which version of RHEL my Amazon Linux is based on.
My GCC version is 4.4.6. This image is a few years old.

It looks like RHEL are still releasing v6.x (in parallel with v7.x) https://access.redhat.com/articles/3078

I guess you should try to target the oldest compiler possible which doesn't require any tricky code changes and doesn't affect performance.

I guess if you absolutely need to use a new compiler (for specific reasons) then that's alright too - We can figure out a way to fallback to WS on older systems where uWS is not supported.

**Comment by alexhultman** [comment]
I think the best solution to this problem will come in PR #88. With that PR we get the best of both worlds: you build from source by default but if that fails it uses the prebuilt binaries. So in most cases you will never need the pre-built binaries.

**Comment by alexhultman** [comment]
@jondubois I opted for a quick fix and just linked statically for now. v0.3.3 should work on any Linux dist.
