### ISSUE TITLE
Incorrect binary data

### ISSUE THREAD

**Issue by henopied** [alexhultman/uWebSockets#77]
Client: 
```
var WebSocket = require('ws');

function onmessage (msg) {
  console.log(msg.data);
  var buf = msg.data;
  console.log(buf.readUInt8(0));
}

var ws = new WebSocket('ws://localhost:8080');
ws.binaryType = 'nodebuffer';
ws.onmessage  = onmessage;
```

Server:
```
var WebSocketServer = require('uws').Server;
var wss = new WebSocketServer({ port: 8080 });

wss.on('connection', function (ws) {
    var buf = new Buffer(1);
    buf.writeUInt8(1, 0);

    ws.send(buf, {binary: true});
});
```
This code should work but instead I get 118 on the client and if i replace uws with ws its fine.

**Comment by alexhultman** [comment]
Ah, nice. I never tried the typed arrays.

**Comment by alexhultman** [comment]
What OS? Things like these are tested with Autobahn.

**Comment by henopied** [comment]
Ubuntu, the buffer isn't only that one byte either from what I can see. I thought Autobahn would catch something like this too.

**Comment by alexhultman** [comment]
I also get 118 and a long buffer. Very strange, will check this out.

**Comment by alexhultman** [comment]
The error is before send even gets its data. I made a change where I added support for all three types of data: String, Buffer, TypedArray. The problem is that is interprets Buffers as TypedArrays. So yes, this is completely broken but good news is this is a very simple thing to fix.

**Comment by alexhultman** [comment]
63198df58a35deffb1dd61d5129cb6eb732bfc36

So the problem was that IsTypedArray() evaluated to true for Buffer, which obviously was pretty wrong. Now it correctly interprets all three types. Will be pushed as an update later on.

**Comment by alexhultman** [comment]
I pushed a new version, update and it should work :+1:

**Comment by henopied** [comment]
@alexhultman Thanks so much for this :). Just wondering will client support be coming in the future?

**Comment by alexhultman** [comment]
Well thanks for finding and reporting this ridiculously broken case :)

I don't think client support is really that important as the most loaded part of a server is... the server :P
