### ISSUE TITLE
uWS::Socket does not fit in STL-containers

### ISSUE THREAD

**Issue by jimmyt857** [alexhultman/uWebSockets#78]
For my use-case, I need to be able to respond to messages on one socket by sending a message from a different socket. I've done this with the following:

```c++
std::map<void*, Connection*> connections();
server.onConnection([this](uWS::Socket socket) {
        connections[socket.socket] = new Connection(socket.socket);
});
server.onMessage([this](uWS::Socket socket, const char *message, size_t length, uWS::OpCode opCode) {
        Connection otherConnection = // Get some connection from our map
        char* response = "something";
        uWS::Socket(otherConnection.socket).send((char*) response, strlen(response), uWS::OpCode::TEXT);
});
```

In other words, I store the socket pointer for each connection and use it later to construct a `uWS::Socket` object for sending.

To make this work, I had to make the `uWS::Socket` constructor and its `socket` pointer public. I'm submitting this issue to ask if you can support my use-case, but I understand that exposing those members might be poor design; perhaps there is a cleaner way?

**Comment by alexhultman** [comment]
I have a similar problem in the Node.js addon code. If you look at nodejs/addon.cpp you see how I subclass the socket to expose its constructor and socket pointer. You could do the same as a quick workaround.

When it comes to the mapping, I would (if possible) instead use socket.setData(void *) to bind data to a socket, that way you remove the lookup cost.

**Comment by alexhultman** [comment]
```c++

struct Socket : uWS::Socket {
    Socket(void *s) : uWS::Socket(s) {}
    Socket(const uWS::Socket &s) : uWS::Socket(s) {}
    void **getSocketPtr() {return &socket;}
};
```

**Comment by jimmyt857** [comment]
Haha, yeah I have no problem using a workaround for now. Thanks for the suggestion, using a subclass is definitely cleaner. Hopefully a solution can be integrated into the library itself eventually?

I need to do the lookup because my Connection objects store a lot of other information about each user's session, which affects the response message. I can probably save myself from allocating a new Socket object each time with setData, though!

**Comment by alexhultman** [comment]
Why are you storing a void * in your map? Why not just store the Socket? Then you wouldn't need to change anything. The size of a Socket is the size of a void *.

**Comment by alexhultman** [comment]
I think the cleanest solution in this case is to just implement the operator< in Socket. That way you could just add the Socket in the map and be done.

**Comment by alexhultman** [comment]
ea73e71f15ac971fe17839802cff92485edc6c95

With this you can do this:

```c++
std::map<uWS::Socket, Connection*> connections();
server.onConnection([this](uWS::Socket socket) {
        connections[socket] = new Connection(socket);
});
server.onMessage([this](uWS::Socket socket, const char *message, size_t length, uWS::OpCode opCode) {
        Connection otherConnection = // Get some connection from our map
        char* response = "something";
        otherConnection.socket.send((char*) response, strlen(response), uWS::OpCode::TEXT);
});
```

**Comment by jimmyt857** [comment]
Unfortunately, using the `uWS::Socket` directly in the map requires a default constructor. For now, I've taken your suggestion of inheriting, i.e.

```c++
struct Socket : uWS::Socket {
   Socket() : uWS::Socket(nullptr) {}
   Socket(const uWS::Socket &s) : uWS::Socket(s) {}
   void const* const getSocketPtr() const {return socket;}
   bool operator==(const Socket &other) const {return socket == other.socket;}
};
```

There is another section of my code where I need to use an unordered_map, so I added the == operator and a hash function. This is fine for now, but eventually you may want to rethink the way Sockets are handed out, because I don't think I'll be the only user who wants to use them outside of the callbacks.

**Comment by alexhultman** [comment]
The sockets are supposed to be used outside the callbacks, of course. And that is what everyone is doing. This issue is not about rethinking anything but rather about adding the proper STL-required operators and constructors to the Socket object so that it can be used with the standard containers.

You shouldn't create workarounds that play with the internals, just send me a PR with the missing constructors and operators and this is not an issue anymore.

**Comment by alexhultman** [comment]
@jimmyt857 With this commit e4fe6d17250183e38cd6122098304274bfeb3303 it should work with std::map, std::unordered_map, std::vector, etc. See if this solves your issues in a clean way.
