### ISSUE TITLE
benchmarks building is limited to gcc and its instructions are not well documented and failing.

### ISSUE THREAD

**Issue by utensil** [alexhultman/uWebSockets#80]
## Compiler limitation

benchmarks building is limited to gcc , but I'm using clang(and `CXX` is set to `clang++`), so I needed to modify the Makefile in `benchmarks` to something like:

```make
CXX ?= g++
default:
	$(CXX) -std=c++11 -O3 bench1.cpp -s -o bench1 -lpthread 
# the rest is similar
```

## Dependency issues

bench1 builds fine without any dependencies.

bench2 requires [WebSocket++](https://github.com/zaphoyd/websocketpp) which in turn requires boost >> 1.41 (my production server default version of boost, I don't know the lower limit of version, but I just switched to the latest version)

bench3 and wsPP are similar to bench2.

uWS refers to missing `../uWS.cpp` and `../utf8.cpp`, the former is possibly just `./uWS.cpp`, but the latter is not present.

**Comment by alexhultman** [comment]
8d978eb3dcd52a55ffdf7e3da01e8cc0f35a3a93

**Comment by alexhultman** [comment]
Now it builds. You need WebSocket++, Boost and I use G++ in this Makefile. On OS X g++ is an alias to clang++.

**Comment by utensil** [comment]
Thanks for the quick fix.

Yeah, g++ alias is the case for Mac, but we need to use g++ and clang++ separately under Linux, and `CXX` is the standard [implicit variable](https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html) for C++ compiler in GNU make and the usage of these variables are also suggested in [GNU Makefile Conventions](https://www.gnu.org/prep/standards/html_node/Utilities-in-Makefiles.html#Utilities-in-Makefiles) for better portability and substitutablity:

> The Makefile rules for building and installation can also use compilers and related programs, but should do so via make variables so that the user can substitute alternatives. Here are some of the programs we mean:

> ```
> ar bison cc flex install ld ldconfig lex
> make makeinfo ranlib texi2dvi yacc
> ```

> Use the following make variables to run those programs:

> ```
> $(AR) $(BISON) $(CC) $(FLEX) $(INSTALL) $(LD) $(LDCONFIG) $(LEX)
> $(MAKE) $(MAKEINFO) $(RANLIB) $(TEXI2DVI) $(YACC)
> ```

I mean, this is not a big deal, but it would be nice if I don't need to substitute `g++` after every `git pull` :smile: , or if we could just use CMake to compile these benchmarks, it automatically uses `CXX` and its variants.

I would create a PR if you're OK with this, and I'll add some build instructions in it too.

**Comment by alexhultman** [comment]
Ah, nice. Did not know about $(CXX) in the Makefiles. It works here.

**Comment by alexhultman** [comment]
Sure add info and request for a pull.

**Comment by utensil** [comment]
Sorry for the delay, PR sent.
