### ISSUE TITLE
Possible race condition in handleUpgrade

### ISSUE THREAD

**Issue by lpinca** [alexhultman/uWebSockets#86]
Every upgrade request registers a new [`onConnection`](https://github.com/alexhultman/uWebSockets/blob/5793d5813da116b58f28911a2eecf73f34e43495/nodejs/dist/uws.js#L268-L278) handler, but [`server.upgrade`](https://github.com/alexhultman/uWebSockets/blob/5793d5813da116b58f28911a2eecf73f34e43495/nodejs/dist/uws.js#L286) is called asynchronously when the socket is closed.

If there are concurrent requests I think that it is possible that the wrong `onConnection` handler will be used.

For example if there are 2 concurrent requests they will both use the `onConnection` handler of the second one.

I haven't tested this so I may be totally wrong.

**Comment by alexhultman** [comment]
You can move the setting of the onConnection to inside the close handler

**Comment by lpinca** [comment]
Yes that is also what I thought.
