### ISSUE TITLE
Implement permessage-deflate

### ISSUE THREAD

**Issue by alexhultman** [alexhultman/uWebSockets#90]
This is a popular extension and is needed to pass Autobahn fully.

**Comment by alexhultman** [comment]
permessage-deflate branch now passes every Autobahn test: http://htmlpreview.github.io/?https://github.com/alexhultman/uWebSockets/blob/permessage-deflate/autobahn/index.html

This needs to be merged back in master and also get some clean-ups.

**Comment by lpinca** [comment]
I didn't look at the code but I guess there is an option to enable/disable permessage-deflate right?
Sometimes the overhead does not worth the effort so having an option to disable it would be nice.

**Comment by alexhultman** [comment]
Yes you specify the server option perMessageDeflate as in ws. This first commit is just initial and will be complemented with options.

**Comment by alexhultman** [comment]
There is no option to control if what you send is going to be compressed or not in ws, right? Send should take an option to specify if you want to compress or not IMO.

**Comment by SEAPUNK** [comment]
There is, I just don't think it's documented. https://github.com/websockets/ws/blob/master/lib/WebSocket.js#L246-L249

**Comment by lpinca** [comment]
@alexhultman ws is spec compliant and allows to compress messages individually as @SEAPUNK pointed out. Other WebSocket implementations like `faye-websocket` only allow to enable it globally.
In Primus we use same approach, that is all or none no control over the single messages.

**Comment by alexhultman** [comment]
Btw, I will default to different settings than ws - this way I can optimize for memory usage and when broadcasting. If you enable "server_no_context_takeover; client_no_context_takeover" then you can share one z-stream for every socket and also, you can pre-compress a shared message when doing mass broadcast like in SocketCluster :+1:

**Comment by lpinca** [comment]
@alexhultman Can I assume that the API for permessage-deflate is finalized?
Are you planning to change it or can I use it as is now in Primus?

**Comment by alexhultman** [comment]
I'm not sure about the settings and I should probably add some kind of option to control if sends are compressed or not. But yeah, pretty much the foundation should be somewhat done.

**Comment by lpinca** [comment]
I think I'll wait untill it ends up in a release. Thanks.

**Comment by lucidrains** [comment]
waiting for this as well

**Comment by alexhultman** [comment]
Yep, I will release this as 0.5.0 soon. I need to fix it up a little first, it will fail when the BUFFER_SIZE is small currently. Since 0.4.1 has been out there for a month now and it seems pretty stable, I guess I need to make sure not to release something less stable. Maybe I should fix this up and release it with permessage-deflate turned off by default. Anyways, this is almost done.

**Comment by alexhultman** [comment]
Option negotiation / inflation should now work. Compression from server is not implemented yet but is not really required to pass all tests.
