### ISSUE TITLE
C++ echo and multithreaded_echo broken

### ISSUE THREAD

**Issue by jimmyt857** [alexhultman/uWebSockets#91]
The current versions of echo.cpp and multithreaded_echo.cpp haven't been updated since the OnDisconnection callback signature has changed, so compilation fails. For example, in multithreaded_echo.cpp, instead of the following line:
```c++
threadedServer[i]->onDisconnection([i](Socket socket) {
```
it should be
```c++
threadedServer[i]->onDisconnection([i](Socket socket, int code, char *message, size_t length) {
```
I would have created a pull request, but this change is so simple it seems easier to let you make it yourself.

**Comment by alexhultman** [comment]
Thanks, this is now fixed.
