### ISSUE TITLE
Fix / optimize memory usage when transferring connection from Node.js

### ISSUE THREAD

**Issue by alexhultman** [alexhultman/uWebSockets#96]
The memory usage completely explodes when putting Node.js as the HTTP server. This needs investigation - it should be consuming the same amount of memory as when using the built-in HTTP server (after explicitly running the GC). There is no reason for this massive memory usage difference.

**Comment by alexhultman** [comment]
Can anyone explain to me why this piece of vanilla Node.js-code is consuming over 1.6 GB of RAM? It runs until it fails due to failed memory allocation. I'm calling the GC every 10k connection and I'm closing the socket - there should be no reason whatsoever for consuming that much RAM!

```javascript
const http = require('http');
const httpServer = http.createServer((request, response) => {
  response.end();
});

var connections = 0;

httpServer.on('upgrade', (request, socket, head) => {
    if (++connections % 10000 == 0) {
        gc();
    }

    socket.end('\r\n\r\n');
});

httpServer.listen(3000);
```

**Comment by alexhultman** [comment]
I'm running bench1 against it and it fails on ~400k connections. Using the built-in HTTP server manages 1 million connections at 290 MB of RAM........ zzzzzzZZZZZzzzZZZZZZzz

**Comment by alexhultman** [comment]
https://github.com/nodejs/node/issues/6632

**Comment by alexhultman** [comment]
It fails to close the socket since bench1 is blocking and not allowing socket.end() to finish *facepalm*

**Comment by SEAPUNK** [comment]
Just a question, sorry if I missed something -- you mentioned that socket.destroy() fixed the memory usage, right? Could it be because socket.end() allows the connection to remain half-open until the client ends the connection on its side? https://nodejs.org/api/net.html#net_event_end

**Comment by alexhultman** [comment]
Yes it was my own fault - socket.end() doesn't close until the client receives which it never did. But I'm still very confused - my sockets from Node.js consume more memory than those from my own HTTP server. They seem to have the same buffer size and all, very strange.

**Comment by SEAPUNK** [comment]
Maybe node is slower to close the connections and clean them up than your server?

**Comment by SEAPUNK** [comment]
(I'm not a C++ programmer, so I don't really know the inner workings of your and node's http servers and such, so apologies in advance for my ignorance)

**Comment by alexhultman** [comment]
My problem is this:

```javascript
httpServer.on('upgrade', (request, socket, head) => {

});
```
vs
```javascript
httpServer.on('upgrade', (request, socket, head) => {
    // dup(socket._handle.fd)
    // socket.destroy();
});
```

They both do the same, they just leave the socket open which lets me measure the memory usage of the first one (keeps the net.Socket) and the lower one (dups the underlying FD, removes the net.Socket).

300k connections of the upper one consumes 1 GB of RAM.
300k connections of the lower one consumes 430 MB of RAM.

The net.Socket is very bloated and we remove it to get the underlying FD only which consumes less memory and can be used from native land. The problem is - it shouldn't be 400 MB, rather about 90 MB (like 300k connections to the built-in HTTP server). It should scale the same in memory, which it doesn't do currently.

**Comment by alexhultman** [comment]
I think I found the issue. Every transfer function call creates a V8 ObjectTemplate and this thing is humongous in memory size and seems to never be GC:d at all. I should probably reuse this template.

**Comment by alexhultman** [comment]
https://bugs.chromium.org/p/v8/issues/detail?id=2221

**Comment by alexhultman** [comment]
Everything adds up now
