### ISSUE TITLE
Rewrite uws.js, use Node.js's HTTP server in all cases

### ISSUE THREAD

**Issue by alexhultman** [alexhultman/uWebSockets#97]
We should use Node.js's HTTP server in all cases.

**Comment by alexhultman** [comment]
Using this base:

```javascript
'use strict';

const http = require('http');
const httpServer = http.createServer((request, response) => {
  response.end();
});

const uws = require('/home/alexhultman/uWebSockets/nodejs/dist/uws.js').uws;
const server = new uws.Server(0);

function noop() {}

class Socket {
	constructor(nativeSocket, nativeServer) {
		this.nativeSocket = nativeSocket;
		this.nativeServer = nativeServer;
		this.onmessage = noop;
		this.onclose = noop;
	}
}

server.onConnection((nativeSocket) => {
	const socket = new Socket(nativeSocket, server);
	server.setData(nativeSocket, socket);
});

httpServer.on('upgrade', (request, socket, head) => {
	const ticket = server.transfer(socket._handle.fd, socket.ssl ? socket.ssl._external : null);
	socket.on('close', (error) => {
		server.upgrade(ticket, request.headers['sec-websocket-key']);
	});
	socket.destroy();
});

httpServer.listen(3000);
```

It requires 577 MB of RAM for 1 million connections, which is identical to the 580 MB of RAM the non-transferred connections requires. However, the current uws.js seems to require 1.2 GB of RAM when transferring connections. It needs a complete rewrite, memory usage should be exactly 580 MB (on my system).

**Comment by alexhultman** [comment]
I don't understand how this is even possible. I cannot get it to use the same amount of memory:

```javascript
'use strict';

const http = require('http');
const httpServer = http.createServer((request, response) => {
  response.end();
});

const uws = require('/home/alexhultman/uWebSockets/nodejs/dist/uws.js').uws;
const server = new uws.Server(0);

function noop() {}

class Socket {
    constructor(nativeSocket, nativeServer) {
        this.nativeSocket = nativeSocket;
        this.nativeServer = nativeServer;
        this.onmessage = noop;
        this.onclose = noop;
    }
}

server.onConnection((nativeSocket) => {
    const socket = new Socket(nativeSocket, server);
    server.setData(nativeSocket, socket);
	
	// this registering of the closure makes the mem usage go from 580 mb to 1.0 gb
	socket.onmessage = (message) => {
		socket.send(message);
	};
});

server.onDisconnection((nativeSocket, code, message, socket) => {
	socket.onclose(code, message);
	server.setData(nativeSocket);
});

httpServer.on('upgrade', (request, socket, head) => {
    const ticket = server.transfer(socket._handle.fd, socket.ssl ? socket.ssl._external : null);
    socket.on('close', (error) => {
        server.upgrade(ticket, request.headers['sec-websocket-key']);
    });
    socket.destroy();
});

httpServer.listen(3000);
```

This piece of code aims to replicate the echo.js server (requires 580 mb memory). This piece of code requires 1.0 gb of memory. It doesn't leak memory as I have connected 1 million connections, disconnected them all, repeated 10 times in a row and it still requires 1.0 gb (it's stable in memory usage). It simply makes no sense that it requires this much memory.

**Comment by alexhultman** [comment]
Compare the code I pasted above with this one that instead makes use of the internal HTTP server (it passes port 3000 to uws.Server). This code only requires about 580 mb of memory and the difference between no onmessage and onmessage is less obvious:

```javascript
'use strict';

const uws = require('/home/alexhultman/uWebSockets/nodejs/dist/uws.js').uws;
const server = new uws.Server(3000);

function noop() {}

class Socket {
    constructor(nativeSocket, nativeServer) {
        this.nativeSocket = nativeSocket;
        this.nativeServer = nativeServer;
        this.onmessage = noop;
        this.onclose = noop;
    }
}

server.onConnection((nativeSocket) => {
    const socket = new Socket(nativeSocket, server);
    server.setData(nativeSocket, socket);
	
	// this registering of the closure makes the mem usage go from 420 mb to 580 mb
	socket.onmessage = (message) => {
		socket.send(message);
	};
});

server.onDisconnection((nativeSocket, code, message, socket) => {
	socket.onclose(code, message);
	server.setData(nativeSocket);
});
```

There is really no reason at all for this massive difference!

**Comment by alexhultman** [comment]
My gut feeling is that I'm capturing `ticket` which is bloating the onmessage closure in the first case, but not in the second case (there is no ticket to capture). Can this be the case? Why would the same closures otherwise occupy different amount of memory? How can I explicitly not capture the ticket? Wtf is a scope chain? Does JS really capture the entire stack and all variables on it at the time of capture? That would be *ridiculous*, but still plausible since JS i dynamic and cannot statically determine what variables the function will access? In C++ you explicitly capture just the variables you specify, or the ones the (static) code references.

**Comment by alexhultman** [comment]
If I throw an error in `onConnection` using both solutions, the output is this:

```
node memory.js 
/home/alexhultman/memory.js:23
    throw new Error('onConnection');
    ^

Error: onConnection
    at /home/alexhultman/memory.js:23:11
    at Socket.<anonymous> (/home/alexhultman/memory.js:41:16)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at TCP._onclose (net.js:484:12)
```
vs
```
node memory.js 
/home/alexhultman/memory.js:23
    throw new Error('onConnection');
    ^

Error: onConnection
    at /home/alexhultman/memory.js:23:11
```
indicating that we are deeper in the stack when using Node.js's HTTP server and thus (If I understand things correctly) create a heavier capture?

**Comment by alexhultman** [comment]
```javascript
var k = 3;
var u = 4;

function f() {
    var x = 5;
    function j() {
        return eval("x + k - u");
    }
    return j();
}

console.log(f());
console.dir(f);
```

This code prints 4, indicating that indeed, JS captures the entire stack. I even use eval to make the code as dynamic as it can possibly be, and still it calculates the correct value. This is a major problem since I want to explicitly force the capture to only capture what I explicitly use. How?

**Comment by alexhultman** [comment]
I talked to the Node.js squad on Gitter and after initially getting the message of how extremely fast, optimized and lightweight JavaScript is shoved down my throat we started to actually discuss the problem and it turns out that JavaScript, like I figured out from experimentation, adds the entire stack to every function, making the size of closures depend on the current depth of the stack. This is insanely inefficient and a suicide for memory usage but explains the difference in closure size.

**Comment by Michael77** [comment]
Hey @alexhultman, I think you may be able to solve the memory issue with functions declared outside of the closure. For example, define an onMessage(socket) function, to be called in onConnection. It will not inherit the closure scope, and you will have to pass only the needed objects as args.

**Comment by alexhultman** [comment]
One idea I have is to queue the upgrade using an libuv async (it would be pretty much like nextTick) and call the onConnection from there.

**Comment by alexhultman** [comment]
Well, that didn't change it. Very strange, the call stack shows that it is being called at the lowest level possible (I throw this error in onConnection to show where it is being called from):

```javascript
node memory.js 
/home/alexhultman/memory.js:24
    throw new Error('asd');
    ^

Error: asd
    at /home/alexhultman/memory.js:24:11
```

**Comment by alexhultman** [comment]
I'm kind of mega frustrated and maybe I should just begin to create an initial version. 1 GB ram per 1 million connections is still like 15x better than ws and we need to get this new update out.

**Comment by alexhultman** [comment]
@Michael77 The problem is that the user has to create a closure because the callback doesn't take the socket as argument:

```javascript
wss.on('connection', function (ws) {
	ws.on('message', function (message) { // this function is a closure capturing ws
		ws.send(message);
	});
});
```

**Comment by Michael77** [comment]
Yeah, I guess there isn't too much you can do to about javascript. You could always port it to GO ^__^

**Comment by alexhultman** [comment]
There has to be something to improve the memory usage but that can happen later on

**Comment by ronkorving** [comment]
The user can use "this" instead of "ws" in the on-message function, voiding the need for a closure object.

**Comment by SEAPUNK** [comment]
It'd have to be a non-arrow function, which people could easily get confused about.

**Comment by ronkorving** [comment]
Sure, just saying :)
